                        ["Button A1"]={template="BBlueOnOff"},
                        ["Button A2"]={template="BBlueOnOff"},
                        ["Button A3"]={template="BBlueOnOff"},
                        ["Button A4"]={template="BBlueOnOff"},
                        ["Button A5"]={template="BBlueOnOff"},
                        ["Button A6"]={template="BBlueOnOff"},
                        ["Button A7"]={template="BBlueOnOff"},
                        ["Button A8"]={template="BBlueOnOff"},
