	["Alligator"]={
		["Default"]={
		},
		["Index"]={
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDOrange"},
			["Button 1-2"]={template="BRedOnOff"},
			["Button 3-2"]={template="BGreenOnOff"},
			["UDVButton 5-2_6-2"]={template="UDOrange"},
			["UDVButton 7-2_8-2"]={template="UDGreen"},
			["UDVButton 7-3_8-3"]={template="UDOrange"},
			["Button 1-4"]={template="BRedOnOff"},
			["Button 3-4"]={template="BRedOnOff"},
			["Button 5-4"]={template="BRedOnOff"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 3-5"]={template="BRedOnOff"},
			["Button 5-5"]={template="BRedOnOff"},
			["Fader 7"]={template="FRed"},
		},
		["HPFilter"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Knob V3"]={template="FYellow"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Knob V6"]={template="FYellow"},
		},
		["BPFilter"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Knob V3"]={template="FYellow"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Knob V6"]={template="FYellow"},
		},
		["LPFilter"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Knob V3"]={template="FYellow"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Knob V6"]={template="FYellow"},
		},
		["HPEffects"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FOrange"},
			["Knob V6"]={template="FRed"},
			["Fader 7"]={template="FRed"},
		},
		["BPEffects"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FOrange"},
			["Knob V6"]={template="FRed"},
			["Fader 7"]={template="FRed"},
		},
		["LPEffects"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FOrange"},
			["Knob V6"]={template="FRed"},
			["Fader 7"]={template="FRed"},
		},
		["Delay"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FGreen"},
			["UDVButton 7-2_8-2"]={template="UDGreen"},
			["Button 1-3"]={template="BGreenOnOff"},
			["Fader 4"]={template="FOrange"},
			["Knob V5"]={template="FOrange"},
		},
		["Phaser"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
		},
		["AmpEnv"]={
			["Fader 3"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
		},
		["DryLevels"]={
			["Fader 2"]={template="FOrange"},
			["Knob V4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
		},
		["FilterEnv"]={
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
		},
		["LFO"]={
			["UDVButton 1-2_2-2"]={template="UDYellow"},
			["Fader 4"]={template="FGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
			["Button 1-5"]={template="BGreenOnOff"},
		},
	},
