	["BV512 Digital Vocoder"]={
		["Default"]={
			["Fader 1"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 2"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 3"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 4"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 5"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 6"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 7"]={template="FVCGreen", bvmap="Fader VC"},
			["Fader 8"]={template="FVCGreen", bvmap="Fader VC"},
		},
		["Index"]={
			["UDVButton 7-1_8-1"]={template="UDNocolor"},
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDEffect"},
			["Button 4-1"]={template="BRedOnOff"},
			["UDVButton 5-1_6-1"]={template="UDEffect"},
			["UDVButton 7-1_8-1"]={template="UDEffect"},
			["Fader 4"]={template="FAmount"},
			["Fader 5"]={template="FAmount"},
			["Knob V6"]={template="FGain"},
			["Fader 7"]={template="FFreq"},
			["Fader 8"]={template="FEffect"},
		},
	},
