	["Polar Dual Pitch Shifter"]={
		["Default"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectSupPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectSupPage"},
		},
		["Index"]={
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDOrange"},
			["UDVButton 1-3_2-3"]={template="UDOrange", inverted=true},
			["UDVButton 5-3_6-3"]={template="UDOrange", inverted=true},
			["Button 8-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
		},
		["Dry Signal"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Knob V4"]={template="FRed"},
			["Knob V5"]={template="FYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Delay Buffer"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 5-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Button 1-4"]={template="BRedOnOff"},
			["Knob V4"]={template="FYellow"},
			["Knob V5"]={template="FYellow"},
		},
		["Shifter *"]={
			["Button 1-1"]={template="BRedOnOff"},
			["Knob V2"]={template="FGreen"},
			["Knob V3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FOrange"},
			["Knob V6"]={template="FYellow"},
			["Knob V7"]={template="FYellow"},
		},
		["Shifter Vol *"]={
			["Knob V2"]={template="FRed"},
			["Knob V3"]={template="FYellow"},
			["Fader 6"]={template="FRed"},
		},
		["Envelope"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FYellow"},
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
			["Button 1-7"]={template="BRedOnOff"},
		},
		["LFO"]={
			["Fader 2"]={template="FGreen"},
			["UDVButton 7-2_8-2"]={template="UDGreen"},
			["Fader 3"]={template="FYellow"},
			["UDVButton 7-4_8-4"]={template="UDOrange"},
			["Button 1-5"]={template="BRedOnOff"},
		},
		["Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 7-3_8-3"]={template="UDGreen", inverted=true},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Fader 6"]={template="FYellow"},
			["Knob V7"]={template="FYellow"},
			["Knob V8"]={template="FYellow"},
		},
	},
