	["RV7000 Advanced Reverb"]={
		["Default"]={
		},
		["Index"]={
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDOrange"},
			["Button 1-2"]={template="BRedOnOff"},
			["Button 2-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FGreen"},
			["Knob V5"]={template="FGreen"},
			["Fader 7"]={template="FOrange"},
		},
		["Reverb"]={
			["UDVButton 1-1_2-1"]={template="UDOrange"},
			["SmallSpace"]={
				["Fader 2"]={template="FOrange"},
				["Fader 3"]={template="FYellow"},
				["UDVButton 7-4_8-4"]={template="UDOrange"},
				["Fader 5"]={template="FGreen"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FYellow"},
			},
			["Room"]={
				["Fader 2"]={template="FOrange"},
				["Fader 3"]={template="FOrange"},
				["UDVButton 7-4_8-4"]={template="UDOrange"},
				["Fader 5"]={template="FOrange"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FYellow"},
			},
			["Hall"]={
				["Fader 2"]={template="FOrange"},
				["Fader 3"]={template="FOrange"},
				["UDVButton 7-4_8-4"]={template="UDOrange"},
				["Fader 5"]={template="FOrange"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FYellow"},
			},
			["Arena"]={
				["Fader 2"]={template="FOrange"},
				["Fader 3"]={template="FOrange"},
				["Fader 4"]={template="FGreen"},
				["Fader 5"]={template="FGreen"},
				["Fader 6"]={template="FAmber"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FAmber"},
			},
			["Plate"]={
				["Fader 5"]={template="FGreen"},
				["Fader 7"]={template="FGreen"},
			},
			["Spring"]={
				["Fader 2"]={template="FOrange"},
				["Fader 3"]={template="FOrange"},
				["Fader 4"]={template="FGreen"},
				["Fader 5"]={template="FGreen"},
				["Button 8-6"]={template="BRedOnOff"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FAmber"},
			},
			["Echo"]={
				["Fader 2"]={template="FOrange"},
				["UDVButton 7-2_8-2"]={template="UDOrange"},
				["Fader 3"]={template="FOrange"},
				["Button 8-4"]={template="BRedOnOff"},
				["Fader 5"]={template="FGreen"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FGreen"},
			},
			["MultiTap"]={
				["Button 8-2"]={template="BRedOnOff"},
				["Fader 3"]={template="FOrange"},
				["Fader 4"]={template="FGreen"},
				["UDVButton 7-5_8-5"]={template="UDOrange"},
				["Fader 6"]={template="FGreen"},
				["UDVButton 7-6_8-6"]={template="UDGreen"},
				["Fader 7"]={template="FAmber"},
				["Knob V8"]={template="FAmber"},
			},
			["Reverse"]={
				["Fader 2"]={template="FOrange"},
				["UDVButton 7-2_8-2"]={template="UDOrange"},
				["Fader 3"]={template="FOrange"},
				["Button 8-6"]={template="BRedOnOff"},
				["Fader 5"]={template="FOrange"},
			},
			["Convolution"]={
				["UDVButton 7-2_8-2"]={template="UDOrange"},
				["Fader 3"]={template="FOrange"},
				["Knob V4"]={template="FOrange"},
				["Fader 5"]={template="FGreen"},
				["UDVButton 7-6_8-6"]={template="UDAmber"},
				["Knob V7"]={template="FGreen"},
				["Fader 8"]={template="FRed"},
			},
		},
		["Eq"]={
			["Knob V2"]={template="FRed"},
			["Fader 3"]={template="FGreen"},
			["Knob V5"]={template="FRed"},
			["Fader 6"]={template="FGreen"},
			["Fader 7"]={template="FOrange"},
		},
		["Gate"]={
			["Fader 1"]={template="FOrange"},
			["Fader 2"]={template="FOrange"},
			["Button 8-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FOrange"},
		},
	},
