	["Synchronous"]={
		["Default"]={
		},
		["Index"]={
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDOrange"},
			["Fader 3"]={template="FRed"},
			["Button 8-4"]={template="BRedOnOff"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FRed"},
		},
		["Dist"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 3-2_4-2"]={template="UDOrange"},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FOrange"},
		},
		["Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 3-2_4-2"]={template="UDOrange"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Fader 7"]={template="FYellow"},
		},
		["Delay"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 3-2"]={template="BRedOnOff"},
			["Button 4-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 8-5"]={template="BRedOnOff"},
			["Fader 6"]={template="FOrange"},
			["Button 8-7"]={template="BRedOnOff"},
			["Knob V8"]={template="FOrange"},
		},
		["Reverb"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Fader 7"]={template="FYellow"},
			["Button 8-8"]={template="BRedOnOff"},
		},
	},
