                        ["Button B1"]={template="BMainPage"},
                        ["Button B2"]={template="BOscPage"},
                        ["Button B3"]={template="BFilterPage"},
                        ["Button B4"]={template="BAmpPage"},
                        ["Button B5"]={template="BLFOPage"},
                        ["Button B6"]={template="BPerformancePage"},
