	["Antidote"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage", helptext="Goto Main"},
			["Button 2-1"]={template="BOscPage", helptext="Goto Osc 1"},
			["Button 3-1"]={template="BOscPage", helptext="Goto Osc 2"},
			["Button 4-1"]={template="BAmpPage", helptext="Goto Mixer"},
			["Button 5-1"]={template="BFilterPage", helptext="Goto Filter"},
		},
		["Index"]={
			["Button 8-1"]={template="BPerformancePage"},
			["Button 8-2"]={template="BPerformancePage"},
			["Button 8-3"]={template="BPerformancePage"},
			["Button 8-4"]={template="BPerformancePage"},
			["Button 8-5"]={template="BPerformancePage"},
		},
		["Main"]={
			["Fader 3"]={template="FYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Osc *"]={
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["UDVButton 3-2_4-2"]={template="UDAmber", inverted=true},
			["UDVButton 5-2_6-2"]={template="UDAmber", inverted=true},
			["UDVButton 1-3_2-3"]={template="UDGreen"},
			["UDVButton 3-3_4-3"]={template="UDGreen"},
			["UDVButton 5-3_6-3"]={template="UDGreen"},
			["Fader 4"]={template="FAmber"},
			["Fader 5"]={template="FAmber"},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FYellow"},
			["Knob V8"]={template="FRed"},
		},
		["Mixer"]={
			["Fader 2"]={template="FRed"},
			["Fader 3"]={template="FRed"},
			["Fader 4"]={template="FAmber"},
			["Fader 5"]={template="FAmber"},
			["Fader 6"]={template="FYellow"},
		},
		["Filter"]={
			["UDVButton 1-2_2-2"]={template="UDGreen", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 4"]={template="FYellow"},
		},
		["Filter Env"]={
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
		},
		["Effects"]={
			["Fader 2"]={template="FAmber"},
			["Button 2-7"]={template="BGreenOnOff"},
			["Button 3-7"]={template="BGreenOnOff"},
			["Button 4-7"]={template="BGreenOnOff"},
			["Button 5-7"]={template="BGreenOnOff"},
			["Button 6-7"]={template="BGreenOnOff"},
			["Button 7-7"]={template="BGreenOnOff"},
			["Button 8-7"]={template="BGreenOnOff"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["EQ/Bass"]={ --EQBass
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDGreen"},
			["UDVButton 5-1_6-1"]={template="UDOrange"},
			["Fader 2"]={template="FRed"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Dist"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDOrange"},
			["UDVButton 5-1_6-1"]={template="UDOrange"},
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Phaser"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDOrange"},
			["UDVButton 5-1_6-1"]={template="UDGreen"},
			["Fader 2"]={template="FGreen"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Chorus"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["Fader 2"]={template="FGreen"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Delay"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDOrange"},
			["UDVButton 5-1_6-1"]={template="UDGreen"},
			["UDVButton 7-1_8-1"]={template="UDGreen"},
			["Fader 2"]={template="FOrange"},
			["Fader 3"]={template="FOrange"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Reverb"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDOrange"},
			["Fader 2"]={template="FOrange"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FYellow"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Comp"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDOrange"},
			["Fader 2"]={template="FOrange"},
			["Fader 4"]={template="FAmber"},
			["Fader 5"]={template="FAmber"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["LFO *"]={
                        ["Fader 3"]={template="FGreen"},
                        ["UDVButton 7-3_8-3"]={template="UDGreen"},
                        ["Knob V4"]={template="FAmber"},
			["Button 1-5"]={template="BGreenOnOff"},
			["Button 1-6"]={template="BGreenOnOff"},
                        ["UDHButton 3-5_3-6"]={template="UDYellow"},
                        ["UDHButton 5-5_5-6"]={template="UDYellow"},
		},
		["Amp Env"]={
                        ["Fader 3"]={template="FRed"},
                        ["Fader 4"]={template="FRed"},
                        ["Fader 5"]={template="FRed"},
                        ["Fader 6"]={template="FRed"},
		},
		["Mod Env"]={
                        ["UDVButton 3-1_4-1"]={template="UDYellow"},
                        ["Fader 3"]={template="FYellow"},
                        ["Fader 4"]={template="FYellow"},
                        ["Fader 5"]={template="FYellow"},
                        ["Fader 5"]={template="FYellow"},
                        ["Knob V8"]={template="FAmber"},
		},
		["Arpeggiator"]={
                        ["UDHButton 3-1_3-2"]={template="UDYellow"},
                        ["UDHButton 5-1_5-2"]={template="UDYellow"},
                        ["UDHButton 6-1_6-2"]={template="UDGreen"},
                        ["UDHButton 7-1_7-2"]={template="UDYellow"},
                        ["Button 8-1"]={template="BGreenOnOff"},
		},
		["Mod Matrix *"]={
			["Button 1-1"]={template="BPerformancePage"},
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
			["Button 4-1"]={template="BPerformancePage"},
			["Button 5-1"]={template="BPerformancePage"},
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["Knob V3"]={template="FAmber"},
			["UDVButton 1-4_2-4"]={template="UDOrange", inverted=true},
		},
	},
