	["DrOctoRex"]={
		["Default"]={
		},
		["Main"]={
			["UDVButton 1-2_2-2"]={template="UDGreen"},
			["UDVButton 1-3_2-3"]={template="UDYellow"},
			-- Select Loop
			["Button 4-3"]={template="BYellowOnOff"},
			["Button 4-4"]={template="BYellowOnOff"},
			["Button 4-5"]={template="BYellowOnOff"},
			["Button 4-6"]={template="BYellowOnOff"},
			["Button 5-3"]={template="BYellowOnOff"},
			["Button 5-4"]={template="BYellowOnOff"},
			["Button 5-5"]={template="BYellowOnOff"},
			["Button 5-6"]={template="BYellowOnOff"},
			-- Right Controls
			["Button 1-7"]={template="BRedOnOff"},
			["Button 5-7"]={template="BYellowOnOff"},
			["UDVButton 7-8_8-8"]={template="FGreen"},
			["Fader 8"]={template="FRed"},
		},
		["AmpEnv"]={
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
			["Fader 7"]={template="FRed"},
		},
		["Osc"]={
			["Knob V2"]={template="FAmber"},
			["UDVButton 1-3_2-3"]={template="UDGreen"},
			["UDVButton 1-4_2-4"]={template="UDGreen"},
		},
		["Loop"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDAmber"},
			["UDVButton 1-4_2-4"]={template="UDGreen"},
			["Fader 8"]={template="FRed"},
		},
		["Performance"]={
			["UDVButton 3-1_4-1"]={template="UDYellow"},
			["UDVButton 7-1_8-1"]={template="UDYellow"},
			["Knob V2"]={template="FGreen"},
			["Knob V3"]={template="FGreen"},
			["Knob V4"]={template="FOrange"},
			["Knob V6"]={template="FYellow"},
			["Knob V7"]={template="FOrange"},
			["Knob V8"]={template="FRed"},
		},
		["Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="FGreen", inverted=true},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
		},
		["FilterEnv"]={
			["Fader 2"]={template="FAmber"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
			["Fader 7"]={template="FGreen"},
		},
		["LFO"]={
			["UDVButton 1-2_2-2"]={template="FYellow", inverted=true},
			["UDVButton 5-2_6-2"]={template="FYellow", inverted=true},
			["Button 1-4"]={template="BRedOnOff"},
			["Fader 5"]={template="FGreen"},
			["UDVButton 7-5_8-5"]={template="FGreen"},
			["Fader 8"]={template="FAmber"},
		},
	},
