	["Europa"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage", helptext="Goto Main"},
			["Button 2-1"]={template="BOscPage", helptext="Goto Engine 1"},
			["Button 3-1"]={template="BOscPage", helptext="Goto Engine 2"},
			["Button 4-1"]={template="BOscPage", helptext="Goto Engine 3"},
		},
		["Main"]={
			["Fader 5"]={template="FMisc"},
			["Fader 8"]={template="FGain"},
		},
		["Index"]={
			["Button 7-1"]={template="BPerformancePage"},
			["Button 7-2"]={template="BPerformancePage"},
			["Button 7-3"]={template="BPerformancePage"},
			["Button 7-4"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["Button 8-2"]={template="BPerformancePage"},
			["Button 8-3"]={template="BPerformancePage"},
			["Button 8-4"]={template="BPerformancePage"},
			["Button 5-5"]={template="BFilterPage"},
			["Button 2-7"]={template="BEffect2Page"},
			["Button 3-7"]={template="BEffect2Page"},
			["Button 4-7"]={template="BEffect2Page"},
		},
		["Mixer"]={
			["Fader 2"]={template="FGain"},
			["Knob V3"]={template="FGain"},
			["Fader 4"]={template="FGain"},
			["Knob V5"]={template="FGain"},
			["Fader 6"]={template="FGain"},
			["Knob V7"]={template="FGain"},
		},
		["Filter"]={
			["Button 5-1"]={template="BRedOnOff"},
			["Button 6-1"]={template="BRedOnOff"},
			["Button 7-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDFreq", inverted=true},
			["Fader 3"]={template="FGain"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FFreq"},
			["UDVButton 1-6_2-6"]={template="UDMisc"},
			["UDVButton 3-6_4-6"]={template="UDMisc"},
			["UDVButton 5-6_6-6"]={template="UDMisc"},
			["UDVButton 3-7_4-7"]={template="UDMisc", inverted=true},
		},
		["Amp"]={
			["Knob V2"]={template="FGain"},
			["Fader 3"]={template="FGain"},
			["Fader 4"]={template="FMisc"},
			["Fader 5"]={template="FGain"},
			["Fader 6"]={template="FGain"},
			["Fader 7"]={template="FGain"},
			["Fader 8"]={template="FGain"},
		},
		["Eng *"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDFreq"},
			["UDVButton 3-3_4-3"]={template="UDFreq"},
			["UDVButton 5-3_6-3"]={template="UDFreq"},
			["UDVButton 1-4_2-4"]={template="UDAmount", inverted=true},
			["UDVButton 7-6_8-6"]={template="UDMisc", inverted=true},
			["Fader 5"]={template="FAmount"},
			["Fader 7"]={template="FMisc"},
			["Fader 8"]={template="FMisc"},
		},
		["Eng * Mod *"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDAmount", inverted=true},
			["Fader 4"]={template="FAmount"},
			["Fader 5"]={template="FMisc"},
			["UDVButton 7-6_8-6"]={template="UDMisc", inverted=true},
		},
		["Eng * Spectral Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 3-2_4-2"]={template="UDFreq", inverted=true},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FMisc"},
			["Fader 6"]={template="FMisc"},
			["UDVButton 7-7_8-7"]={template="UDMisc", inverted=true},
			["Fader 8"]={template="FMisc"},
		},
		["Eng * Harmonics"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDAmount", inverted=true},
			["Fader 4"]={template="FMisc"},
			["Fader 5"]={template="FAmount"},
		},
		["Eng * Unison"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDEffect", inverted=true},
			["UDVButton 1-4_2-4"]={template="UDEffect"},
			["Fader 5"]={template="FEffect"},
			["Fader 6"]={template="FFreq"},
			["Fader 7"]={template="FEffect"},
		},
		["LFO *"]={
			["Button 5-1"]={template="BLFOPage", helptext="Goto LFO 1"},
			["Button 6-1"]={template="BLFOPage", helptext="Goto LFO 2"},
			["Button 7-1"]={template="BLFOPage", helptext="Goto LFO 3"},
			["UDVButton 1-2_2-2"]={template="UDMisc"},
			["Button 6-2"]={template="BRedOnOff"},
			["Button 7-2"]={template="BRedOnOff"},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FFreq"},
			["UDVButton 7-3_8-3"]={template="UDFreq"},
			["Fader 4"]={template="FEffect"},
		},
		["Env *"]={
			["Button 5-1"]={template="BEnvPage", helptext="Goto Env 1"},
			["Button 6-1"]={template="BEnvPage", helptext="Goto Env 2"},
			["Button 7-1"]={template="BEnvPage", helptext="Goto Env 3"},
			["Button 8-1"]={template="BEnvPage", helptext="Goto Env 4"},
			["Fader 3"]={template="FFreq"},
			["UDVButton 7-4_8-4"]={template="UDFreq"},
		},
		["Effects"]={
			["Button 2-7"]={template="BRedOnOff"},
			["Button 3-7"]={template="BRedOnOff"},
			["Button 4-7"]={template="BRedOnOff"},
			["Button 5-7"]={template="BRedOnOff"},
			["Button 6-7"]={template="BRedOnOff"},
			["Button 7-7"]={template="BRedOnOff"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Phaser"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 5-1_6-1"]={template="UDEffect"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FFreq"},
			["Fader 6"]={template="FEffect"},
			["Fader 7"]={template="FAmount"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Dist"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 5-1_6-1"]={template="UDEffect"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FFreq"},
			["Fader 7"]={template="FAmount"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Eq"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FMisc"},
			["Fader 7"]={template="FAmount"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Delay"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 4-1"]={template="BRedOnOff"},
			["Button 6-1"]={template="BRedOnOff"},
			["UDVButton 3-2_4-2"]={template="UDFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FEffect"},
			["Fader 7"]={template="FAmount"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Comp"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FMisc"},
			["Fader 4"]={template="FMisc"},
			["Fader 6"]={template="FEffect"},
			["Fader 7"]={template="FEffect"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Reverb"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FMisc"},
			["Fader 7"]={template="FAmount"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Mod Matrix *"]={
			["Button 1-1"]={template="BPerformancePage"},
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
			["Button 4-1"]={template="BPerformancePage"},
			["Button 5-1"]={template="BPerformancePage"},
			["Button 6-1"]={template="BPerformancePage"},
			["Button 7-1"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["UDVButton 1-2_2-2"]={template="UDAmount", inverted=true},
			["Knob V3"]={template="FAmount"},
			["UDVButton 1-4_2-4"]={template="UDEffect", inverted=true},
			["Knob V5"]={template="FEffect"},
			["UDVButton 1-6_2-6"]={template="UDEffect", inverted=true},
			["Knob V7"]={template="FEffect"},
			["UDVButton 1-8_2-8"]={template="UDMisc", inverted=true},
		},
	},
