	["Grain"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage", helptext="Goto Main"},
			["Button 1-2"]={template="BRedOnOff"},
		},
		["Main"]={
			["Fader 3"]={template="FYellow"},
			["UDVButton 7-7_7-7"]={template="UDGreen"},
			["Fader 8"]={template="FRed"},
		},
		["Index"]={
			["Button 1-2"]={template="BAmpPage"},
			["Button 7-1"]={template="BPerformancePage"},
			["Button 7-2"]={template="BPerformancePage"},
			["Button 7-3"]={template="BPerformancePage"},
			["Button 7-4"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["Button 8-2"]={template="BPerformancePage"},
			["Button 8-3"]={template="BPerformancePage"},
			["Button 8-4"]={template="BPerformancePage"},
		},
		["Sample"]={
			["Fader 1"]={template="FYellow"},
			["Fader 2"]={template="FYellow"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FRed"},
			["UDVButton 1-5_2-5"]={template="UDAmber", inverted=true},
			["Fader 6"]={template="FGreen"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BRedOnOff"},
		},
		["Grains"]={
			["UDVButton 1-1_2-1"]={template="UDAmber", inverted=true},
			["Spectral Grains"]={
				["Fader 2"]={template="FAmber"},
				["Fader 3"]={template="FGreen"},
				["Button 1-4"]={template="BRedOnOff"},
				["UDVButton 7-4_8-4"]={template="UDAmber"},
				["Fader 5"]={template="FYellow"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FYellow"},
			},
			["Grain Oscillator"]={
				["Fader 2"]={template="FRed"},
				["Fader 3"]={template="FOrange"},
				["Fader 4"]={template="FAmber"},
				["Fader 5"]={template="FAmber"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FGreen"},
				["Fader 8"]={template="FYellow"},
			},
			["Long Grains"]={
				["Fader 2"]={template="FRed"},
				["Fader 3"]={template="FOrange"},
				["Fader 4"]={template="FAmber"},
				["Fader 5"]={template="FAmber"},
				["Fader 6"]={template="FAmber"},
			},
			["Tape"]={
				["Fader 6"]={template="FAmber"},
			},
		},
		["Pitch"]={
			["UDVButton 1-2_2-2"]={template="UDGreen"},
			["UDVButton 1-3_2-3"]={template="UDGreen"},
			["UDVButton 1-4_2-4"]={template="UDGreen"},
			["Fader 6"]={template="FYellow"},
		},
		["Osc"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDGreen"},
			["UDVButton 1-4_2-4"]={template="UDAmber"},
			["Fader 6"]={template="FYellow"},
		},
		["Mixer"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FRed"},
			["Button 1-4"]={template="BRedOnOff"},
			["Fader 5"]={template="FRed"},
		},
		["Filter"]={
			["UDVButton 1-2_2-2"]={template="UDGreen", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["UDVButton 1-6_2-6"]={template="UDYellow"},
			["UDVButton 1-7_2-7"]={template="UDYellow"},
			["UDVButton 2-8_1-8"]={template="UDYellow"},
		},
		["Amp"]={
			["Fader 2"]={template="FRed"},
			["Fader 3"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FYellow"},
			["Knob V8"]={template="FRed"},
		},
		["LFO *"]={
			["Button 5-1"]={template="BLFOPage", helptext="Goto LFO 1"},
			["Button 6-1"]={template="BLFOPage", helptext="Goto LFO 2"},
			["Button 7-1"]={template="BLFOPage", helptext="Goto LFO 3"},
			["UDVButton 1-2_2-2"]={template="UDYellow"},
			["Button 6-2"]={template="BRedOnOff"},
			["Button 7-2"]={template="BRedOnOff"},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FGreen"},
			["UDVButton 7-3_8-3"]={template="UDGreen"},
			["Fader 4"]={template="FOrange"},
		},
		["Env *"]={
			["Button 5-1"]={template="BEnvPage", helptext="Goto Env 1"},
			["Button 6-1"]={template="BEnvPage", helptext="Goto Env 2"},
			["Button 7-1"]={template="BEnvPage", helptext="Goto Env 3"},
			["Button 8-1"]={template="BEnvPage", helptext="Goto Env 4"},
			["Fader 3"]={template="FGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
		},
		["Effects"]={
			["Button 2-7"]={template="BRedOnOff"},
			["Button 3-7"]={template="BRedOnOff"},
			["Button 4-7"]={template="BRedOnOff"},
			["Button 5-7"]={template="BRedOnOff"},
			["Button 6-7"]={template="BRedOnOff"},
			["Button 7-7"]={template="BRedOnOff"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Phaser"]={
			["UDVButton 5-1_6-1"]={template="UDOrange"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Dist"]={
			["UDVButton 5-1_6-1"]={template="UDOrange"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FGreen"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Eq"]={
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FYellow"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Delay"]={
			["Button 4-1"]={template="BRedOnOff"},
			["Button 6-1"]={template="BRedOnOff"},
			["UDVButton 3-2_4-2"]={template="UDGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FOrange"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Comp"]={
			["Fader 3"]={template="FYellow"},
			["Fader 4"]={template="FYellow"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FOrange"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Reverb"]={
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
		},
		["Mod Matrix *"]={
			["Button 1-1"]={template="BPerformancePage"},
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
			["Button 4-1"]={template="BPerformancePage"},
			["Button 5-1"]={template="BPerformancePage"},
			["Button 6-1"]={template="BPerformancePage"},
			["Button 7-1"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["Knob V3"]={template="FAmber"},
			["UDVButton 1-4_2-4"]={template="UDOrange", inverted=true},
			["Knob V5"]={template="FOrange"},
			["UDVButton 1-6_2-6"]={template="UDOrange", inverted=true},
			["Knob V7"]={template="FOrange"},
			["UDVButton 1-8_2-8"]={template="UDYellow", inverted=true},
		},
	},
