	["Malstrom"]={
		["Default"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
		},
		["Main"]={
			["Fader 3"]={template="FYellow"},
			["Button 8-2"]={template="BYellowOnOff"},
			["Fader 7"]={template="FYellow"},
			["Fader 8"]={template="FAmber"},
		},
		["Osc *"]={
			["Button 8-1"]={template="BYellowOnOff"},
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FAmber"},
			["Knob V4"]={template="FAmber"},
			["UDVButton 7-5_8-5"]={template="UDGreen"},
			["UDVButton 7-6_8-6"]={template="UDGreen"},
			["UDVButton 7-7_8-7"]={template="UDGreen"},
			["Button 8-8"]={template="BYellowOnOff"},
		},
		["Osc A"]={
			["Button 7-8"]={template="BYellowOnOff"},
		},
		["Osc * Env"]={
			["Fader 3"]={template="FAmber"},
			["Fader 4"]={template="FAmber"},
			["Fader 5"]={template="FAmber"},
			["Fader 6"]={template="FAmber"},
			["Fader 8"]={template="FRed"},
		},
		["Filter *"]={
			["Button 5-1"]={template="BFilterPage"},
			["Button 6-1"]={template="BFilterPage"},
			["Button 1-2"]={template="BYellowOnOff"},
			["UDVButton 7-4_8-4"]={template="UDGreen", inverted=true},
			["Button 8-5"]={template="BYellowOnOff"},
			["Button 8-6"]={template="BYellowOnOff"},
			["Fader 7"]={template="FGreen"},
			["Fader 8"]={template="FOrange"},
		},
		["Filter Env"]={
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
			["Button 8-7"]={template="BYellowOnOff"},
			["Fader 8"]={template="FAmber"},
		},
		["Mod *"]={
			["Button 5-1"]={template="BLFOPage"},
			["Button 6-1"]={template="BLFOPage"},
			["Button 1-2"]={template="BYellowOnOff"},
			["UDVButton 3-2_4-2"]={template="UDYellow"},
			["Fader 3"]={template="FGreen"},
			["Knob V4"]={template="FYellow"},
			["Knob V5"]={template="FYellow"},
			["Knob V6"]={template="FYellow"},
			["Knob V7"]={template="FYellow"},
			["Button 1-8"]={template="BYellowOnOff"},
			["Button 2-8"]={template="BYellowOnOff"},
			["UDVButton 7-8_8-8"]={template="UDYellow"},
		},
		["Shaper"]={
			["Button 1-2"]={template="BYellowOnOff"},
			["UDVButton 5-2_6-2"]={template="FOrange", inverted=true},
			["Fader 8"]={template="FOrange"},
		},
		["Velocity"]={
			["UDVButton 7-8_8-8"]={template="UDYellow"},
		},
		["ModWheel"]={
			["UDVButton 7-8_8-8"]={template="UDYellow"},
		},
	},
