	["NN-19"]={
		["Default"]={
		},
		["Index"]={
			["Button 1-4"]={template="BPerformancePage"},
		},
		["Main"]={
			["Fader 1"]={template="FYellow"},
			["UDVButton 1-2_2-2"]={template="UDYellow"},
			["Fader 3"]={template="FAmber"},
			["UDVButton 1-4_2-4"]={template="UDAmber", inverted=true},
			["Button 1-5"]={template="BRedOnOff"},
			["UDVButton 1-6_2-6"]={template="UDYellow", inverted=true},
			["UDVButton 1-7_2-7"]={template="UDYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Amp"]={
			["Fader 1"]={template="FRed"},
			["Fader 3"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
		},
		["Controller"]={
			["Knob V2"]={template="FGreen"},
			["Knob V3"]={template="FYellow"},
			["Knob V4"]={template="FRed"},
			["UDVButton 1-5_2-5"]={template="UDYellow", inverted=true},
		},
		["Mod Wheel"]={
			["Knob V2"]={template="FGreen"},
			["Knob V3"]={template="FOrange"},
			["Knob V4"]={template="FGreen"},
			["Knob V5"]={template="FRed"},
			["Knob V6"]={template="FYellow"},
		},
		["Velocity"]={
			["Knob V2"]={template="FGreen"},
			["Knob V3"]={template="FGreen"},
			["Knob V4"]={template="FRed"},
			["Knob V5"]={template="FRed"},
			["Knob V6"]={template="FAmber"},
		},
		["Osc"]={
			["Fader 1"]={template="FAmber"},
			["Button 1-2"]={template="BRedOnOff"},
			["Knob V3"]={template="FYellow"},
			["UDVButton 1-5_2-5"]={template="UDGreen"},
			["UDVButton 1-6_2-6"]={template="UDGreen"},
			["UDVButton 1-7_2-7"]={template="UDGreen"},
			["Button 1-8"]={template="BRedOnOff"},
		},
		["Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["UDVButton 1-5_2-5"]={template="UDGreen", inverted=true},
			["Fader 6"]={template="FYellow"},
		},
		["Filter Envelope"]={
			["Fader 2"]={template="FGreen"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Button 1-6"]={template="BRedOnOff"},
			["Fader 7"]={template="FAmber"},
		},
		["LFO"]={
			["UDVButton 1-2_2-2"]={template="UDYellow", inverted=true},
			["Button 1-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
			["Fader 5"]={template="FYellow"},
			["UDVButton 1-6_2-6"]={template="UDYellow", inverted=true},
		},
	},
