	["Pangea"]={
		["Default"]={
		},
		["Main"]={
			["Fader 8"]={template="FRed"},
		},
		["Instrument"]={
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["Fader 4"]={template="FAmber"},
			["UDVButton 1-5_2-5"]={template="UDGreen"},
			["UDVButton 1-6_2-6"]={template="UDGreen"},
			["UDVButton 1-7_2-7"]={template="UDGreen"},
		},
		["Amp"]={
			["Fader 2"]={template="FYellow"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
			["Fader 7"]={template="FRed"},
		},
		["Filter"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDGreen", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 6"]={template="FYellow"},
			["Fader 7"]={template="FYellow"},
			["Fader 8"]={template="FYellow"},
		},
		["Filter Envelope"]={
			["Fader 2"]={template="FYellow"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
			["Fader 7"]={template="FGreen"},
		},
		["Delay"]={
			["Button 1-1"]={template="BRedOnOff"},
			["Fader 2"]={template="FGreen"},
			["UDVButton 7-2_8-2"]={template="UDGreen"},
			["Button 1-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FOrange"},
			["Button 1-5"]={template="BRedOnOff"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FOrange"},
		},
		["Reverb"]={
			["Button 1-1"]={template="BRedOnOff"},
			["Fader 2"]={template="FOrange"},
			["Fader 3"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
			["Fader 8"]={template="FOrange"},
		},
		["Mod Wheel"]={
			["Fader 2"]={template="FAmber"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FRed"},
		},
	},
