	["Parsec"]={
		["Default"]={
			["Knob V6"]={template="FRed"},
			["Fader 7"]={template="FYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Index"]={
			["Button 8-1"]={template="BPerformancePage"},
			["Button 8-2"]={template="BPerformancePage"},
			["Button 8-3"]={template="BPerformancePage"},
			["Button 8-4"]={template="BPerformancePage"},
			["Button 8-5"]={template="BPerformancePage"},
			["Button 8-6"]={template="BPerformancePage"},
			["Button 8-7"]={template="BPerformancePage"},
			["Button 8-8"]={template="BPerformancePage"},
		},
		["Amp Envelope"]={
			["Fader 2"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
			["Fader 7"]={template="FRed"},
		},
		["Generator *"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FAmber"},
			["UDVButton 1-4_2-4"]={template="UDGreen"},
			["UDVButton 3-4_4-4"]={template="UDGreen"},
			["UDVButton 5-4_6-4"]={template="UDGreen"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FGreen"},
			["Fader 8"]={template="FYellow"},
		},
		["Sound Engine *"]={
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["Fader 3"]={template="FAmber"},
			["Fader 4"]={template="FAmber"},
			["UDVButton 1-5_2-5"]={template="UDAmber", inverted=true},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FAmber"},
		},
		["Reverb"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FAmber"},
			["Fader 7"]={template="FRed"},
		},
		["Delay"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 1-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
			["Fader 5"]={template="FOrange"},
			["Fader 8"]={template="FOrange"},
		},
		["LFO *"]={
			["UDVButton 1-2_2-2"]={template="UDYellow"},
			["Fader 3"]={template="FOrange"},
			["Button 1-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
		},
		["Env 1"]={
			["Fader 3"]={template="FYellow"},
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
		},
		["Env 2"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FOrange"},
			["Fader 6"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
		},
		["Mod Matrix *"]={
			["Button 1-1"]={template="BPerformancePage"},
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
			["Button 4-1"]={template="BPerformancePage"},
			["Button 5-1"]={template="BPerformancePage"},
			["Button 6-1"]={template="BPerformancePage"},
			["Button 7-1"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["Knob V3"]={template="FAmber"},
			["UDVButton 1-4_2-4"]={template="UDOrange", inverted=true},
			["Knob V5"]={template="FOrange"},
			["UDVButton 1-6_2-6"]={template="UDOrange", inverted=true},
			["Knob V7"]={template="FOrange"},
			["UDVButton 1-8_2-8"]={template="UDYellow", inverted=true},
		},
	},
