	["PX7"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage", helptext="Goto Main"},
			["Button 2-1"]={template="BOscPage", helptext="Goto OP 6"},
			["Button 3-1"]={template="BOscPage", helptext="Goto OP 5"},
			["Button 4-1"]={template="BOscPage", helptext="Goto OP 4"},
			["Button 5-1"]={template="BOscPage", helptext="Goto OP 3"},
			["Button 6-1"]={template="BOscPage", helptext="Goto OP 2"},
			["Button 7-1"]={template="BOscPage", helptext="Goto OP 1"},
		},
		["Main"]={
			["UDVButton 1-2_2-2"]={template="FAmber"},
			["Fader 3"]={template="FYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Op*"]={
			["Button 8-2"]={template="BGreenOnOff"},
			["UDVButton 7-3_8-3"]={template="UDGreen"},
			["UDVButton 7-4_8-4"]={template="UDGreen"},
			["UDVButton 7-5_8-5"]={template="UDGreen"},
			["Knob V7"]={template="FRed"},
			["Fader 8"]={template="FRed"},
		},
		["LFO"]={
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FGreen"},
			["UDVButton 7-3_8-3"]={template="UDGreen"},
			["Fader 4"]={template="FYellow"},
			["UDVButton 1-5_2-5"]={template="UDYellow", inverted=true},
		},
	},
