	["Radical Piano"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage"},
		},
		["Main"]={
			["Fader 2"]={template="FOrange"},
			["Fader 4"]={template="FAmber"},
			["UDVButton 7-5_8-5"]={template="UDAmber"},
			["Knob V6"]={template="FAmber"},
			["UDVButton 7-7_8-7"]={template="UDAmber"},
			["Fader 8"]={template="FRed"},
		},
		["Envelope"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Fader 4"]={template="FRed"},
			["Knob V5"]={template="FRed"},
			["Knob V6"]={template="FRed"},
		},
		["Velocity"]={
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FYellow"},
			["Knob V6"]={template="FYellow"},
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
		},
		["Tune"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Knob V4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
		},
		["Resonance"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Knob V4"]={template="FGreen"},
			["Knob V5"]={template="FAmber"},
		},
		["Mechanics"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Knob V4"]={template="FAmber"},
			["Knob V5"]={template="FAmber"},
			["Knob V6"]={template="FAmber"},
		},
		["Eq"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 1-2"]={template="BRedOnOff"},
			["Knob V4"]={template="FRed"},
			["Knob V5"]={template="FRed"},
			["Knob V6"]={template="FRed"},
		},
		["Ambience"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["UDVButton 7-3_8-3"]={template="UDOrange", inverted=true},
			["Fader 4"]={template="FOrange"},
		},
		["Output"]={
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Fader 3"]={template="FOrange"},
			["Knob V4"]={template="FOrange"},
		},
	},
