	["Revival"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage"},
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
			["Button 5-1"]={template="BOscPage"},
			["Button 6-1"]={template="BFilterPage"},
			["Button 7-1"]={template="BFilterPage"},
			["Button 8-1"]={template="BFilterPage"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
		},
		["Index"]={
			["Button 2-4"]={template="BFilterPage"},
			["Button 3-4"]={template="BFilterPage"},
			["Button 4-4"]={template="BFilterPage"},
			["Button 5-4"]={template="BFilterPage"},
			["Button 2-5"]={template="BFilterModPage"},
			["Button 3-5"]={template="BFilterModPage"},
			["Button 4-5"]={template="BFilterModPage"},
			["Button 5-5"]={template="BFilterModPage"},
			["Button 2-6"]={template="BFilterModPage"},
			["Button 3-6"]={template="BFilterModPage"},
			["Button 4-6"]={template="BFilterModPage"},
			["Button 5-6"]={template="BFilterModPage"},
			["Button 2-7"]={template="BFilterModPage"},
			["Button 3-7"]={template="BFilterModPage"},
			["Button 4-7"]={template="BFilterModPage"},
			["Button 5-7"]={template="BFilterModPage"},
		},
		["Main"]={
			-- S1/S2 switches
			["Button 6-2"]={template="BYellowOnOff"},
			["Button 6-3"]={template="BYellowOnOff"},
			-- Attack Vib/Trem switches
			["Button 7-2"]={template="BYellowOnOff"},
			["Button 7-3"]={template="BYellowOnOff"},
			-- Rotator switches
			["Button 8-2"]={template="BRedOnOff"},
			["Button 8-3"]={template="BRedOnOff"},
			-- R1/R2 knobs
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FYellow"},
			["BigFader 8"]={template="FRed"},
		},
		["Voicing 1"]={
			["Button 2-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="FAmber",inverted=true},
			["UDVButton 3-2_4-2"]={template="FAmber",inverted=true},
			["UDVButton 5-2_6-2"]={template="FYellow",inverted=true},
			["UDVButton 7-2_8-2"]={template="FAmber",inverted=true},
			["Fader 4"]={template="FYellow"},
			["Fader 7"]={template="FYellow"},
		},
		["Voicing 2"]={
			["Fader 1"]={template="FYellow"},
			["Fader 2"]={template="FOrange"},
			["Fader 3"]={template="FYellow"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FOrange"},
			["Fader 8"]={template="FGreen"},
		},
		["Pri/Sec"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDAmber",inverted=true},
			["Knob V4"]={template="FAmber"},
			["Fader 6"]={template="FGreen"},
			["Button 1-7"]={template="BRedOnOff"},
		},
		["Solos"]={
			["Button 8-2"]={template="BSoloRevival"},
			["Button 8-4"]={template="BSoloRevival"},
			["Button 8-6"]={template="BSoloRevival"},
			["Button 8-8"]={template="BSoloRevival"},
		},
		["Attack"]={
			["UDVButton 1-2_2-2"]={template="UDAmber",inverted=true},
			["Fader 3"]={template="FRed"},
			["Fader 5"]={template="FAmber"},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BRedOnOff"},
		},
		["Primary"]={
			["UDVButton 1-2_2-2"]={template="UDAmber",inverted=true},
			["Fader 3"]={template="FRed"},
			["Fader 7"]={template="FAmber"},
		},
		["Secondary"]={
			["UDVButton 1-2_2-2"]={template="UDAmber",inverted=true},
			["Fader 3"]={template="FRed"},
			["Fader 7"]={template="FAmber"},
		},
		["Release"]={
			["UDVButton 1-2_2-2"]={template="UDAmber",inverted=true},
			["Fader 3"]={template="FRed"},
			["Fader 5"]={template="FAmber"},
			["Fader 6"]={template="FAmber"},
			["Fader 7"]={template="FAmber"},
			["Button 1-8"]={template="BRedOnOff"},
		},
		["* Drawbars Lower"]={
			["Button 7-1"]={template="BOscPage"},
			["Button 8-1"]={template="BOscPage"},
			["Drawbar 2"]={template="FAmber"},
			["Drawbar 3"]={template="FAmber"},
			["Drawbar 4"]={template="FGreen"},
			["Drawbar 5"]={template="FGreen"},
			["Drawbar 6"]={template="FYellow"},
			["Drawbar 7"]={template="FGreen"},
			["Drawbar 8"]={template="FYellow"},
		},
		["* Drawbars Upper"]={
			["Button 7-1"]={template="BOscPage"},
			["Button 8-1"]={template="BOscPage"},
			["Drawbar 2"]={template="FYellow"},
			["Drawbar 3"]={template="FOrange"},
			["Drawbar 4"]={template="FGreen"},
		},
		["* Mod Enable"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 1-3"]={template="BRedOnOff"},
			["Button 1-4"]={template="BRedOnOff"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 1-6"]={template="BRedOnOff"},
			["Button 1-7"]={template="BRedOnOff"},
			["Button 1-8"]={template="BRedOnOff"},
			["Button 2-2"]={template="BRedOnOff"},
			["Button 2-3"]={template="BRedOnOff"},
			["Button 2-4"]={template="BRedOnOff"},
			["Button 3-2"]={template="BRedOnOff"},
			["Button 3-3"]={template="BRedOnOff"},
			["Button 3-4"]={template="BRedOnOff"},
			["Button 3-5"]={template="BRedOnOff"},
			["Button 3-6"]={template="BRedOnOff"},
			["Button 3-7"]={template="BRedOnOff"},
			["Button 3-8"]={template="BRedOnOff"},
			["Button 4-2"]={template="BRedOnOff"},
			["Button 4-3"]={template="BRedOnOff"},
			["Button 4-4"]={template="BRedOnOff"},
			["Button 5-2"]={template="BRedOnOff"},
			["Button 5-3"]={template="BRedOnOff"},
			["Button 5-4"]={template="BRedOnOff"},
			["Button 5-5"]={template="BRedOnOff"},
			["Button 5-6"]={template="BRedOnOff"},
			["Button 5-7"]={template="BRedOnOff"},
			["Button 5-8"]={template="BRedOnOff"},
			["Button 6-2"]={template="BRedOnOff"},
			["Button 6-3"]={template="BRedOnOff"},
			["Button 6-4"]={template="BRedOnOff"},
		},
		["* Mod *"]={
			["UDVButton 5-2_6-2"]={template="UDGreen", inverted=true},
			["UDVButton 7-2_8-2"]={template="UDOrange", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
			["Fader 7"]={template="FOrange"},
			["Fader 8"]={template="FGreen"},
		},
		["Effects"]={
			["Button 8-4"]={template="BRedOnOff"},
			["Fader 5"]={template="FOrange"},
			["Button 2-7"]={template="BRedOnOff"},
			["Button 3-7"]={template="BRedOnOff"},
			["Button 4-7"]={template="BRedOnOff"},
			["Button 5-7"]={template="BRedOnOff"},
			["Button 6-7"]={template="BRedOnOff"},
			["Button 7-7"]={template="BRedOnOff"},
		},
		["PreAmp"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDOrange", inverted=true},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FAmber"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FOrange"},
		},
		["Phaser"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDOrange", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FOrange"},
		},
		["ModFilter"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDOrange", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FOrange"},
			["UDVButton 1-5_2-5"]={template="UDGreen"},
			["UDVButton 7-5_8-5"]={template="UDYellow"},
			["Fader 6"]={template="FYellow"},
			["Fader 7"]={template="FGreen"},
			["UDVButton 7-7_8-7"]={template="UDGreen"},
		},
		["Speaker"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDOrange", inverted=true},
			["Fader 3"]={template="FOrange"},
			["Knob V4"]={template="FOrange"},
			["Fader 5"]={template="FOrange"},
			["Knob V7"]={template="FOrange"},
		},
		["Reverb"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDOrange", inverted=true},
			["Fader 3"]={template="FOrange"},
			["Knob V4"]={template="FOrange"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FOrange"},
		},
		["Delay"]={
			["Button 1-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDOrange", inverted=true},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FOrange"},
		},
	},
