	["Subtractor"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage"},
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscModPage"},
			["Button 5-1"]={template="BFilterPage"},
		},
		["Index"]={
			["Button 1-3"]={template="BPerformancePage"},
			["Button 1-4"]={template="BPerformancePage"},
		},
		["Main"]={
			["Button 8-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Osc *"]={
			["Knob V2"]={template="FAmber"},
			["UDVButton 1-3_2-3"]={template="UDAmber", inverted=true},
			["UDVButton 3-3_4-3"]={template="UDAmber"},
			["UDVButton 3-4_4-4"]={template="UDGreen"},
			["UDVButton 3-5_4-5"]={template="UDGreen"},
			["UDVButton 3-6_4-6"]={template="UDGreen"},
			["Button 8-3"]={template="BRedOnOff"},
			["Button 8-6"]={template="BRedOnOff"},
			["Fader 7"]={template="FAmber"},
			["Knob V8"]={template="FRed"},
		},
		["Osc 2"]={
			["Button 8-1"]={template="BRedOnOff"},
		},
		["Noise"]={
			["Fader 2"]={template="FGreen"},
			["Fader 3"]={template="FAmber"},
			["Fader 4"]={template="FRed"},
		},
		["Filter"]={
			["Fader 2"]={template="FGreen"},
			["Fader 3"]={template="FOrange"},
			["UDVButton 5-4_6-4"]={template="UDGreen",inverted=true},
			["Fader 5"]={template="FYellow"},
			["Button 8-6"]={template="BRedOnOff"},
		},
		["Filter 2"]={
			["Button 8-1"]={template="BRedOnOff"},
			["Fader 2"]={template="FGreen"},
			["Fader 3"]={template="FOrange"},
		},
		["Filter Env"]={
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
			["Button 8-7"]={template="BRedOnOff"},
			["Fader 8"]={template="FAmber"},
		},
		["Amp Env"]={
			["Fader 3"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
		},
		["Mod Env"]={
			["Fader 2"]={template="FYellow"},
			["Fader 3"]={template="FYellow"},
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FAmber"},
			["UDVButton 5-7_6-7"]={template="UDYellow", inverted=true},
			["Button 8-7"]={template="BRedOnOff"},
		},
		["LFO 1"]={
			["UDVButton 3-2_4-2"]={template="UDYellow", inverted=true},
			["UDVButton 7-2_8-2"]={template="UDYellow", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FAmber"},
			["Button 8-5"]={template="BRedOnOff"},
		},
		["LFO 2"]={
			["UDVButton 7-2_8-2"]={template="UDYellow", inverted=true},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FAmber"},
			["Fader 6"]={template="FOrange"},
			["Fader 7"]={template="FYellow"},
		},
		["ExtMod"]={
			["UDVButton 7-2_8-2"]={template="UDYellow", inverted=true},
		},
		["Velocity *"]={
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
		},
	},
