	["Thor"]={
		["Default"]={
			["Button 1-1"]={template="BMainPage"},
			["Button 2-1"]={template="BOscPage"},
			["Button 3-1"]={template="BOscPage"},
			["Button 4-1"]={template="BOscPage"},
		},
		["Main"]={
			["UDVButton 1-2_1-2"]={template="UDYellow"},
			["UDVButton 3-2_4-2"]={template="UDYellow3"},
			["UDVButton 5-2_6-2"]={template="UDYellow", inverted=true},
			["UDVButton 7-2_8-2"]={template="UDYellow3"},
			["Fader 3"]={template="FYellow"},
			["Button 1-4"]={template="BGreenOnOff"},
			["Button 2-4"]={template="BGreenOnOff"},
			["Button 8-4"]={template="BRedOnOff"},
			["Button 8-5"]={template="BRedOnOff"},
			["Fader 6"]={template="FYellow"},
			["Fader 7"]={template="FYellow"},
			["Fader 8"]={template="FRed"},
		},
		["Osc *"]={
			["UDVButton 1-2_2-2"]={template="UDAmber", inverted=true},
			["UDVButton 1-3_2-3"]={template="UDYellow"},
			["UDVButton 1-4_2-4"]={template="UDGreen"},
			["UDVButton 1-5_2-5"]={template="UDGreen"},
			["UDVButton 1-6_2-6"]={template="UDGreen"},
			["Fader 8"]={template="FOrange"},
			["Analog"]={
				["UDVButton 7-3_8-3"]={template="UDAmber", inverted=true},
				["Fader 7"]={template="FAmber"},
			},
			["Wavetable"]={
				["UDVButton 7-3_8-3"]={template="UDAmber", inverted=true},
				["Button 8-5"]={template="BRedOnOff"},
				["Fader 7"]={template="FAmber"},
			},
			["Phase Modulation"]={
				["UDVButton 7-3_8-3"]={template="UDAmber"},
				["UDVButton 7-4_8-4"]={template="UDAmber"},
				["Fader 7"]={template="FAmber"},
			},
			["FM Pair"]={
				["UDVButton 7-3_8-3"]={template="UDAmber"},
				["UDVButton 7-4_8-4"]={template="UDAmber"},
				["Fader 7"]={template="FAmber"},
			},
			["Multi Oscillator"]={
				["UDVButton 7-3_8-3"]={template="UDAmber", inverted=true},
				["UDVButton 7-5_8-5"]={template="UDAmber", inverted=true},
				["Fader 7"]={template="FAmber"},
			},
			["Noise"]={
				["UDVButton 7-3_8-3"]={template="UDAmber", inverted=true},
				["Fader 7"]={template="FAmber"},
			},
		},
		["Filter *"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Button 5-1"]={template="BRedOnOff"},
			["Button 6-1"]={template="BRedOnOff"},
			["Button 7-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDGreen", inverted=true},
			["Low Pass"]={
				["Fader 3"]={template="FRed"},
				["Fader 4"]={template="FGreen"},
				["Fader 5"]={template="FOrange"},
				["Button 1-6"]={template="BGreenOnOff"},
				["UDVButton 3-6_4-6"]={template="UDGreen", inverted=true},
				["Button 1-8"]={template="BGreenOnOff"},
				["UDVButton 3-8_4-8"]={template="FYellow"},
				["UDVButton 5-8_6-8"]={template="FYellow"},
				["UDVButton 7-8_8-8"]={template="FYellow"},
			},
			["State Variable"]={
				["Fader 3"]={template="FRed"},
				["Fader 4"]={template="FGreen"},
				["Fader 5"]={template="FOrange"},
				["Button 1-6"]={template="BGreenOnOff"},
				["UDVButton 3-6_4-6"]={template="UDGreen", inverted=true},
				["Fader 7"]={template="FOrange"},
				["Button 1-8"]={template="BGreenOnOff"},
				["UDVButton 3-8_4-8"]={template="FYellow"},
				["UDVButton 5-8_6-8"]={template="FYellow"},
				["UDVButton 7-8_8-8"]={template="FYellow"},
			},
			["Comb"]={
				["Fader 3"]={template="FRed"},
				["Fader 4"]={template="FGreen"},
				["Fader 5"]={template="FOrange"},
				["Button 1-6"]={template="BGreenOnOff"},
				["UDVButton 3-6_4-6"]={template="UDGreen", inverted=true},
				["UDVButton 3-8_4-8"]={template="FYellow"},
				["UDVButton 5-8_6-8"]={template="FYellow"},
				["UDVButton 7-8_8-8"]={template="FYellow"},
			},
			["Formant"]={
				["Fader 3"]={template="FRed"},
				["Fader 4"]={template="FOrange"},
				["Fader 6"]={template="FOrange"},
				["Fader 7"]={template="FOrange"},
				["UDVButton 3-8_4-8"]={template="FYellow"},
				["UDVButton 5-8_6-8"]={template="FYellow"},
				["UDVButton 7-8_8-8"]={template="FYellow"},
			},
		},
		["Filter 2"]={
			["Button 8-1"]={template="BRedOnOff"},
		},
		["Filter Env"]={
			["Button 2-2"]={template="BGreenOnOff"},
			["Fader 3"]={template="FGreen"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FGreen"},
			["Fader 6"]={template="FGreen"},
		},
		["Mixer"]={
			["Knob V3"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
		},
		["Amp"]={
			["UDVButton 3-2_4-2"]={template="UDRed"},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FYellow"},
			["Fader 4"]={template="FRed"},
			["Knob V5"]={template="FRed"},
		},
		["Amp Env"]={
			["Button 2-2"]={template="BGreenOnOff"},
			["Fader 3"]={template="FRed"},
			["Fader 4"]={template="FRed"},
			["Fader 5"]={template="FRed"},
			["Fader 6"]={template="FRed"},
		},
		["Mod Env"]={
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FYellow"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
		},
		["Global Env"]={ -- Global Env
			["Button 2-1"]={template="BGreenOnOff"},
			["Button 3-1"]={template="BGreenOnOff"},
			["Fader 2"]={template="FOrange"},
			["Fader 3"]={template="FYellow"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
			["Fader 7"]={template="FYellow"},
		},
		["LFO *"]={
                        ["UDVButton 3-1_4-1"]={template="UDYellow"},
			["Button 6-1"]={template="BGreenOnOff"},
			["Button 7-1"]={template="BGreenOnOff"},
                        ["Fader 3"]={template="FGreen"},
                        ["Fader 4"]={template="FOrange"},
		},
		["LFO 1"]={
                        ["Fader 5"]={template="FYellow"},
		},
		["Step Sequencer"]={
			-- Sequence select
			["Button 1-1"]={template="BRedOnOff"},
			["Button 1-2"]={template="BRedOnOff"},
			["Button 1-3"]={template="BRedOnOff"},
			["Button 1-4"]={template="BRedOnOff"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 1-6"]={template="BRedOnOff"},
			["Button 1-7"]={template="BRedOnOff"},
			["Button 1-8"]={template="BRedOnOff"},
			["Button 2-1"]={template="BRedOnOff"},
			["Button 2-2"]={template="BRedOnOff"},
			["Button 2-3"]={template="BRedOnOff"},
			["Button 2-4"]={template="BRedOnOff"},
			["Button 2-5"]={template="BRedOnOff"},
			["Button 2-6"]={template="BRedOnOff"},
			["Button 2-7"]={template="BRedOnOff"},
			["Button 2-8"]={template="BRedOnOff"},
			-- Controls
			["Button 8-1"]={template="BRedOnOff"},
                        ["UDVButton 7-2_8-2"]={template="UDOrange"},
                        ["UDVButton 7-3_8-3"]={template="UDOrange", inverted=true},
			["Button 8-4"]={template="BGreenOnOff"},
                        ["UDVButton 7-5_8-5"]={template="UDGreen"},
                        ["UDVButton 7-6_8-6"]={template="UDAmber"},
                        ["UDVButton 7-7_8-7"]={template="UDGreen", inverted=true},
                        ["UDVButton 7-8_8-8"]={template="UDYellow"},
			-- Sequence Knobs
			["Note"]={
				["UDVButton 3-1_4-1"]={template="UDGreen"},
				["UDVButton 3-2_4-2"]={template="UDGreen"},
				["UDVButton 3-3_4-3"]={template="UDGreen"},
				["UDVButton 3-4_4-4"]={template="UDGreen"},
				["UDVButton 3-5_4-5"]={template="UDGreen"},
				["UDVButton 3-6_4-6"]={template="UDGreen"},
				["UDVButton 3-7_4-7"]={template="UDGreen"},
				["UDVButton 3-8_4-8"]={template="UDGreen"},
				["UDVButton 5-1_6-1"]={template="UDGreen"},
				["UDVButton 5-2_6-2"]={template="UDGreen"},
				["UDVButton 5-3_6-3"]={template="UDGreen"},
				["UDVButton 5-4_6-4"]={template="UDGreen"},
				["UDVButton 5-5_6-5"]={template="UDGreen"},
				["UDVButton 5-6_6-6"]={template="UDGreen"},
				["UDVButton 5-7_6-7"]={template="UDGreen"},
				["UDVButton 5-8_6-8"]={template="UDGreen"},
			},
			["Velocity"]={
				["UDVButton 3-1_4-1"]={template="UDAmber"},
				["UDVButton 3-2_4-2"]={template="UDAmber"},
				["UDVButton 3-3_4-3"]={template="UDAmber"},
				["UDVButton 3-4_4-4"]={template="UDAmber"},
				["UDVButton 3-5_4-5"]={template="UDAmber"},
				["UDVButton 3-6_4-6"]={template="UDAmber"},
				["UDVButton 3-7_4-7"]={template="UDAmber"},
				["UDVButton 3-8_4-8"]={template="UDAmber"},
				["UDVButton 5-1_6-1"]={template="UDAmber"},
				["UDVButton 5-2_6-2"]={template="UDAmber"},
				["UDVButton 5-3_6-3"]={template="UDAmber"},
				["UDVButton 5-4_6-4"]={template="UDAmber"},
				["UDVButton 5-5_6-5"]={template="UDAmber"},
				["UDVButton 5-6_6-6"]={template="UDAmber"},
				["UDVButton 5-7_6-7"]={template="UDAmber"},
				["UDVButton 5-8_6-8"]={template="UDAmber"},
			},
			["GateLen"]={
				["UDVButton 3-1_4-1"]={template="UDOrange"},
				["UDVButton 3-2_4-2"]={template="UDOrange"},
				["UDVButton 3-3_4-3"]={template="UDOrange"},
				["UDVButton 3-4_4-4"]={template="UDOrange"},
				["UDVButton 3-5_4-5"]={template="UDOrange"},
				["UDVButton 3-6_4-6"]={template="UDOrange"},
				["UDVButton 3-7_4-7"]={template="UDOrange"},
				["UDVButton 3-8_4-8"]={template="UDOrange"},
				["UDVButton 5-1_6-1"]={template="UDOrange"},
				["UDVButton 5-2_6-2"]={template="UDOrange"},
				["UDVButton 5-3_6-3"]={template="UDOrange"},
				["UDVButton 5-4_6-4"]={template="UDOrange"},
				["UDVButton 5-5_6-5"]={template="UDOrange"},
				["UDVButton 5-6_6-6"]={template="UDOrange"},
				["UDVButton 5-7_6-7"]={template="UDOrange"},
				["UDVButton 5-8_6-8"]={template="UDOrange"},
			},
			["StepDur"]={
				["UDVButton 3-1_4-1"]={template="UDGreen"},
				["UDVButton 3-2_4-2"]={template="UDGreen"},
				["UDVButton 3-3_4-3"]={template="UDGreen"},
				["UDVButton 3-4_4-4"]={template="UDGreen"},
				["UDVButton 3-5_4-5"]={template="UDGreen"},
				["UDVButton 3-6_4-6"]={template="UDGreen"},
				["UDVButton 3-7_4-7"]={template="UDGreen"},
				["UDVButton 3-8_4-8"]={template="UDGreen"},
				["UDVButton 5-1_6-1"]={template="UDGreen"},
				["UDVButton 5-2_6-2"]={template="UDGreen"},
				["UDVButton 5-3_6-3"]={template="UDGreen"},
				["UDVButton 5-4_6-4"]={template="UDGreen"},
				["UDVButton 5-5_6-5"]={template="UDGreen"},
				["UDVButton 5-6_6-6"]={template="UDGreen"},
				["UDVButton 5-7_6-7"]={template="UDGreen"},
				["UDVButton 5-8_6-8"]={template="UDGreen"},
			},
			["Curve1"]={
				["UDVButton 3-1_4-1"]={template="UDYellow"},
				["UDVButton 3-2_4-2"]={template="UDYellow"},
				["UDVButton 3-3_4-3"]={template="UDYellow"},
				["UDVButton 3-4_4-4"]={template="UDYellow"},
				["UDVButton 3-5_4-5"]={template="UDYellow"},
				["UDVButton 3-6_4-6"]={template="UDYellow"},
				["UDVButton 3-7_4-7"]={template="UDYellow"},
				["UDVButton 3-8_4-8"]={template="UDYellow"},
				["UDVButton 5-1_6-1"]={template="UDYellow"},
				["UDVButton 5-2_6-2"]={template="UDYellow"},
				["UDVButton 5-3_6-3"]={template="UDYellow"},
				["UDVButton 5-4_6-4"]={template="UDYellow"},
				["UDVButton 5-5_6-5"]={template="UDYellow"},
				["UDVButton 5-6_6-6"]={template="UDYellow"},
				["UDVButton 5-7_6-7"]={template="UDYellow"},
				["UDVButton 5-8_6-8"]={template="UDYellow"},
			},
			["Curve2"]={
				["UDVButton 3-1_4-1"]={template="UDYellow"},
				["UDVButton 3-2_4-2"]={template="UDYellow"},
				["UDVButton 3-3_4-3"]={template="UDYellow"},
				["UDVButton 3-4_4-4"]={template="UDYellow"},
				["UDVButton 3-5_4-5"]={template="UDYellow"},
				["UDVButton 3-6_4-6"]={template="UDYellow"},
				["UDVButton 3-7_4-7"]={template="UDYellow"},
				["UDVButton 3-8_4-8"]={template="UDYellow"},
				["UDVButton 5-1_6-1"]={template="UDYellow"},
				["UDVButton 5-2_6-2"]={template="UDYellow"},
				["UDVButton 5-3_6-3"]={template="UDYellow"},
				["UDVButton 5-4_6-4"]={template="UDYellow"},
				["UDVButton 5-5_6-5"]={template="UDYellow"},
				["UDVButton 5-6_6-6"]={template="UDYellow"},
				["UDVButton 5-7_6-7"]={template="UDYellow"},
				["UDVButton 5-8_6-8"]={template="UDYellow"},
			},
		},
		["Shaper"]={
			["Button 2-2"]={template="BGreenOnOff"},
                        ["UDVButton 5-2_6-2"]={template="UDOrange", inverted=true},
                        ["Fader 3"]={template="FOrange"},
			["UDVButton 7-4_8-4"]={template="UDRed"},
		},
		["Delay"]={
			["Button 2-2"]={template="BGreenOnOff"},
			["Button 4-2"]={template="BGreenOnOff"},
                        ["Fader 3"]={template="FGreen"},
                        ["Fader 4"]={template="FOrange"},
                        ["Fader 5"]={template="FGreen"},
                        ["Fader 6"]={template="FAmber"},
                        ["Fader 7"]={template="FOrange"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
		},
		["Chorus"]={
			["Button 2-2"]={template="BGreenOnOff"},
                        ["Fader 3"]={template="FGreen"},
                        ["Fader 4"]={template="FOrange"},
                        ["Fader 5"]={template="FGreen"},
                        ["Fader 6"]={template="FAmber"},
                        ["Fader 7"]={template="FOrange"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
		},
	},
