	["Antidote"]={
		["Default"]={
{% if lptype == "mini" %}
			["Button 1-1"]={template="BMainPage", helptext="Goto Main"},
			["Button 2-1"]={template="BOscPage", helptext="Goto Osc 1"},
			["Button 3-1"]={template="BOscPage", helptext="Goto Osc 2"},
			["Button 4-1"]={template="BAmpPage", helptext="Goto Mixer"},
			["Button 5-1"]={template="BFilterPage", helptext="Goto Filter"},
{% else %}
                        ["Button B1"]={template="BMainPage"},
                        ["Button B2"]={template="BOscPage"},
                        ["Button B3"]={template="BOscPage"},
                        ["Button B4"]={template="BAmpPage"},
                        ["Button B5"]={template="BFilterPage"},
                        ["Button B6"]={template="BLFOPage"},
                        ["Button B7"]={template="BPerformancePage"},
                        ["Button B8"]={template="BEffectPage"},
{% endif %}
		},
		["Index"]={
			["Button 8-1"]={template="BPerformancePage"},
			["Button 8-2"]={template="BPerformancePage"},
			["Button 8-3"]={template="BPerformancePage"},
			["Button 8-4"]={template="BPerformancePage"},
			["Button 8-5"]={template="BPerformancePage"},
		},
		["Main"]={
			["Fader 3"]={template="FMisc"},
			["Fader 8"]={template="FGain"},
		},
		["Osc *"]={
			["UDVButton 1-2_2-2"]={template="UDAmount", inverted=true},
			["UDVButton 3-2_4-2"]={template="UDAmount", inverted=true},
			["UDVButton 5-2_6-2"]={template="UDAmount", inverted=true},
			["UDVButton 1-3_2-3"]={template="UDFreq"},
			["UDVButton 3-3_4-3"]={template="UDFreq"},
			["UDVButton 5-3_6-3"]={template="UDFreq"},
			["Fader 4"]={template="FAmount"},
			["Fader 5"]={template="FAmount"},
			["Fader 6"]={template="FAmount"},
			["Fader 7"]={template="FMisc"},
			["Knob V8"]={template="FGain"},
		},
		["Mixer"]={
			["Fader 2"]={template="FGain"},
			["Fader 3"]={template="FGain"},
			["Fader 4"]={template="FAmount"},
			["Fader 5"]={template="FAmount"},
			["Fader 6"]={template="FMisc"},
		},
		["Filter"]={
			["UDVButton 1-2_2-2"]={template="UDFreq", inverted=true},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 4"]={template="FMisc"},
		},
		["Filter Env"]={
			["Fader 2"]={template="FAmount"},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FFreq"},
			["Fader 6"]={template="FFreq"},
		},
		["Effects"]={
{% if lptype == "mini" %}
			["Fader 2"]={template="FAmount"},
			["Button 2-7"]={template="BGreenOnOff"},
			["Button 3-7"]={template="BGreenOnOff"},
			["Button 4-7"]={template="BGreenOnOff"},
			["Button 5-7"]={template="BGreenOnOff"},
			["Button 6-7"]={template="BGreenOnOff"},
			["Button 7-7"]={template="BGreenOnOff"},
			["Button 8-7"]={template="BGreenOnOff"},
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
			["Button 8-1"]={template="BGreenOnOff"},
			["Button 8-2"]={template="BGreenOnOff"},
			["Button 8-3"]={template="BGreenOnOff"},
			["Button 8-4"]={template="BGreenOnOff"},
			["Button 8-5"]={template="BGreenOnOff"},
			["Button 8-6"]={template="BGreenOnOff"},
			["Button 8-7"]={template="BGreenOnOff"},
			["Fader 8"]={template="FAmount"},
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["EQ/Bass"]={ --EQBass
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDFreq"},
			["UDVButton 5-1_6-1"]={template="UDEffect"},
			["Fader 2"]={template="FGain"},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FGain"},
			["Fader 6"]={template="FGain"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["Dist"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDEffect"},
			["UDVButton 5-1_6-1"]={template="UDEffect"},
			["Fader 2"]={template="FAmount"},
			["Fader 3"]={template="FEffect"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FFreq"},
			["Fader 6"]={template="FAmount"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["Phaser"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDEffect"},
			["UDVButton 5-1_6-1"]={template="UDFreq"},
			["Fader 2"]={template="FFreq"},
			["Fader 3"]={template="FEffect"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FMisc"},
			["Fader 6"]={template="FEffect"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["Chorus"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["Fader 2"]={template="FFreq"},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FMisc"},
			["Fader 6"]={template="FEffect"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["Delay"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDEffect"},
			["UDVButton 5-1_6-1"]={template="UDFreq"},
			["UDVButton 7-1_8-1"]={template="UDFreq"},
			["Fader 2"]={template="FEffect"},
			["Fader 3"]={template="FEffect"},
			["Fader 5"]={template="FFreq"},
			["Fader 6"]={template="FAmount"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["Reverb"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDEffect"},
			["Fader 2"]={template="FEffect"},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FFreq"},
			["Fader 6"]={template="FMisc"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["Comp"]={
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 3-1_4-1"]={template="UDEffect"},
			["Fader 2"]={template="FEffect"},
			["Fader 4"]={template="FAmount"},
			["Fader 5"]={template="FAmount"},
			["Fader 7"]={template="FEffect"},
{% if lptype == "mini" %}
			["Button 1-8"]={template="BMainEffectPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 5-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffectPage"},
{% else %}
{% include "devices/instrument/antidote/confmap_bottommenu_effects.lua" %}
{% endif %}
		},
		["LFO *"]={
                        ["Fader 3"]={template="FFreq"},
                        ["UDVButton 7-3_8-3"]={template="UDFreq"},
                        ["Knob V4"]={template="FAmount"},
			["Button 1-5"]={template="BGreenOnOff"},
			["Button 1-6"]={template="BGreenOnOff"},
                        ["UDHButton 3-5_3-6"]={template="UDMisc"},
                        ["UDHButton 5-5_5-6"]={template="UDMisc"},
		},
		["Amp Env"]={
                        ["Fader 3"]={template="FGain"},
                        ["Fader 4"]={template="FGain"},
                        ["Fader 5"]={template="FGain"},
                        ["Fader 6"]={template="FGain"},
		},
		["Mod Env"]={
                        ["UDVButton 3-1_4-1"]={template="UDMisc"},
                        ["Fader 3"]={template="FMisc"},
                        ["Fader 4"]={template="FMisc"},
                        ["Fader 5"]={template="FMisc"},
                        ["Fader 5"]={template="FMisc"},
                        ["Knob V8"]={template="FAmount"},
		},
		["Arpeggiator"]={
                        ["UDHButton 3-1_3-2"]={template="UDMisc"},
                        ["UDHButton 5-1_5-2"]={template="UDMisc"},
                        ["UDHButton 6-1_6-2"]={template="UDFreq"},
                        ["UDHButton 7-1_7-2"]={template="UDMisc"},
                        ["Button 8-1"]={template="BGreenOnOff"},
		},
		["Mod Matrix *"]={
			["Button 1-1"]={template="BPerformancePage"},
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
			["Button 4-1"]={template="BPerformancePage"},
			["Button 5-1"]={template="BPerformancePage"},
			["UDVButton 1-2_2-2"]={template="UDAmount", inverted=true},
			["Knob V3"]={template="FAmount"},
			["UDVButton 1-4_2-4"]={template="UDEffect", inverted=true},
		},
	},
