	["Master Section"]={
		["Default"]={
		},
		["Index"]={
			["Button 1-1"]={template="BMainPage"},
			["Button 1-2"]={template="BAmpPage"},
			["Button 1-3"]={template="BAmpPage"},
			["Button 1-5"]={template="BPerformancePage"},
			["Button 8-1"]={template="BYellow"},
			["Button 8-2"]={template="BYellow"},
			["Button 1-7"]={template="BEffectPage"},
			["Button 2-7"]={template="BEffectPage"},
			["Button 3-7"]={template="BEffectPage"},
			["Button 4-7"]={template="BEffectPage"},
			["Button 5-7"]={template="BEffectPage"},
			["Button 6-7"]={template="BEffectPage"},
			["Button 7-7"]={template="BEffectPage"},
			["Button 8-7"]={template="BEffectPage"},
		},
		["Main"]={
			["Vu"]={
				["Meter 1"]={template="FGreen"},
				["Meter 2"]={template="FGreen"},
			},
			["Peak"]={
				["Meter 1"]={template="FOrange", bvmap="MeterPeak"},
				["Meter 2"]={template="FOrange", bvmap="MeterPeak"},
			},
			["Button 6-4"]={template="BAmpPage"},
			["Button 7-4"]={template="BAmpPage"},
			["Button 8-4"]={template="BRedOnOff"},
			["UDVButton 1-6_2-6"]={template="BRed", inverted=true},
			["UDVButton 1-7_2-7"]={template="BOrange", inverted=true},
			["Fader 5"]={template="FRed"},
			["Button 8-6"]={template="BMute"},
			["Button 8-7"]={template="BSolo"},
			["Button 8-8"]={template="BRedOnOff"},
		},
		["Channel Mutes & Solos"]={
			["Button 1-1"]={template="BMute"},
			["Button 1-2"]={template="BMute"},
			["Button 1-3"]={template="BMute"},
			["Button 1-4"]={template="BMute"},
			["Button 1-5"]={template="BMute"},
			["Button 1-6"]={template="BMute"},
			["Button 1-7"]={template="BMute"},
			["Button 1-8"]={template="BMute"},
	
			["Button 2-1"]={template="BSolo"},
			["Button 2-2"]={template="BSolo"},
			["Button 2-3"]={template="BSolo"},
			["Button 2-4"]={template="BSolo"},
			["Button 2-5"]={template="BSolo"},
			["Button 2-6"]={template="BSolo"},
			["Button 2-7"]={template="BSolo"},
			["Button 2-8"]={template="BSolo"},

			["Button 3-1"]={template="BMute"},
			["Button 3-2"]={template="BSolo"},
		},
		["Channel Faders"]={
		},
		["Master Compressor"]={
                        ["Button 1-2"]={template="BRedOnOff"},
                        ["Button 4-2"]={template="BRedOnOff"},
                        ["Fader 3"]={template="FOrange"},
                        ["UDVButton 1-4_2-4"]={template="FOrange"},
                        ["UDVButton 1-5_2-5"]={template="FYellow"},
                        ["UDVButton 1-6_2-6"]={template="FYellow"},
                        ["Fader 7"]={template="FRed"},
                        ["Meter 8"]={template="FRed"},
		},
		["Master Send"]={
                        ["Fader 1"]={template="FGreen"},
                        ["Fader 2"]={template="FGreen"},
                        ["Fader 3"]={template="FGreen"},
                        ["Fader 4"]={template="FGreen"},
                        ["Fader 5"]={template="FGreen"},
                        ["Fader 6"]={template="FGreen"},
                        ["Fader 7"]={template="FGreen"},
                        ["Fader 8"]={template="FGreen"},
		},
		["Master Insert"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 3-2"]={template="BRedOnOff"},
			["Button 5-2"]={template="BRedOnOff"},
			["Button 6-2"]={template="BRedOnOff"},
			["Button 7-2"]={template="BRedOnOff"},
			["Button 8-2"]={template="BRedOnOff"},
		},
		["Send Return *"]={
			["Button 1-2"]={template="BMute"},
                        ["Fader 3"]={template="FOrange"},
                        ["Knob V4"]={template="FOrange"},
                        ["Meter 8"]={template="FGreen"},
		},

	},
