local item_conf_map = {
{% include "lua/include/confmap_default.lua" %}
{% include "devices/reason/reason-master-section/reason-master-section.lua" %}
{% include "devices/reason/reason-mix-channel/reason-mix-channel.lua" %}
{% include "devices/instrument/antidote/antidote-bottommenu-effects.lua" %}
{% include "devices/instrument/antidote/antidote.lua" %}
{% include "devices/instrument/combinator/combinator.lua" %}
{% include "devices/instrument/drrex/drrex.lua" %}
{% include "devices/instrument/europa/europa-bottommenu-osc.lua" %}
{% include "devices/instrument/europa/europa-grain-bottommenu-effects.lua" %}
{% include "devices/instrument/europa/europa-grain-effects.lua" %}
{% include "devices/instrument/europa/europa.lua" %}
{% include "devices/instrument/grain/grain.lua" %}
{% include "devices/instrument/humana/humana.lua" %}
{% include "devices/instrument/id8/id8.lua" %}
{% include "devices/instrument/klang/klang.lua" %}
{% include "devices/instrument/kong/kong.lua" %}
{% include "devices/instrument/malstrom/malstrom.lua" %}
{% include "devices/instrument/nn19/nn19.lua" %}
{% include "devices/instrument/nnxt/nnxt.lua" %}
{% include "devices/instrument/pangea/pangea.lua" %}
{% include "devices/instrument/parsec/parsec.lua" %}
{% include "devices/instrument/px7/px7.lua" %}
{% include "devices/instrument/radicalpiano/radicalpiano.lua" %}
{% include "devices/instrument/redrum/redrum.lua" %}
{% include "devices/instrument/revival/revival.lua" %}
{% include "devices/instrument/subtractor/subtractor.lua" %}
{% include "devices/instrument/thor/thor-bottommenu-effects.lua" %}
{% include "devices/instrument/thor/thor.lua" %}
{% include "devices/effect/alligator/alligator.lua" %}
{% include "devices/effect/audiomatic/audiomatic.lua" %}
{% include "devices/effect/bv512digitalvocoder/bv512digitalvocoder.lua" %}
{% include "devices/effect/cf-101chorus-flanger/cf-101chorus-flanger.lua" %}
{% include "devices/effect/comp-01compressor-limiter/comp-01compressor-limiter.lua" %}
{% include "devices/effect/d-11foldbackdistortion/d-11foldbackdistortion.lua" %}
{% include "devices/effect/ddl-1digitaldelayline/ddl-1digitaldelayline.lua" %}
{% include "devices/effect/ecf-42filter/ecf-42filter.lua" %}
{% include "devices/effect/mclasscompressor/mclasscompressor.lua" %}
{% include "devices/effect/mclassequalizer/mclassequalizer.lua" %}
{% include "devices/effect/mclassmaximizer/mclassmaximizer.lua" %}
{% include "devices/effect/mclassstereoimager/mclassstereoimager.lua" %}
{% include "devices/effect/neptunepitchadjuster/neptunepitchadjuster.lua" %}
{% include "devices/effect/peq-2twobandparametriceq/peq-2twobandparametriceq.lua" %}
{% include "devices/effect/ph-90phaser/ph-90phaser.lua" %}
{% include "devices/effect/polardualpitchshifter/polardualpitchshifter.lua" %}
{% include "devices/effect/pulveriser/pulveriser.lua" %}
{% include "devices/effect/rv-7digitalreverb/rv-7digitalreverb.lua" %}
{% include "devices/effect/rv7000advancedreverb/rv7000advancedreverb.lua" %}
{% include "devices/effect/saturationknob/saturationknob.lua" %}
{% include "devices/effect/scream4distortion/scream4distortion.lua" %}
{% include "devices/effect/softtubeamp/softtubeamp.lua" %}
{% include "devices/effect/softtubebassamp/softtubebassamp.lua" %}
{% include "devices/effect/synchronous/synchronous.lua" %}
{% include "devices/effect/theecho/theecho.lua" %}
{% include "devices/effect/un-16unison/un-16unison.lua" %}
{% include "devices/utilities/matrix/matrix.lua" %}
{% include "devices/utilities/rpg8/rpg8.lua" %}
}
