                        ["Button B1"]={template="BMainPage"},
                        ["Button B2"]={template="BEffectPage"},
                        ["Button B3"]={template="BFilterPage"},
                        ["Button B4"]={template="BEffectPage"},
                        ["Button B5"]={template="BEffectPage"},
