                        ["Button B1"]={template="BMainPage"},
                        ["Button B2"]={template="BOscPage"},
                        ["Button B3"]={template="BOscPage"},
                        ["Button B4"]={template="BPerformancePage"},
                        ["Button B5"]={template="BPerformancePage"},
                        ["Button B6"]={template="BAmpPage"},
                        ["Button B7"]={template="BEffectPage"},
                        ["Button B8"]={template="BEffectPage"},
