	["Alligator"]={
		["Default"]={
		},
		["Index"]={
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDEffect"},
			["Button 1-2"]={template="BRedOnOff"},
			["Button 3-2"]={template="BGreenOnOff"},
			["UDVButton 5-2_6-2"]={template="UDEffect"},
			["UDVButton 7-2_8-2"]={template="UDFreq"},
			["UDVButton 7-3_8-3"]={template="UDEffect"},
			["Button 1-4"]={template="BRedOnOff"},
			["Button 3-4"]={template="BRedOnOff"},
			["Button 5-4"]={template="BRedOnOff"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 3-5"]={template="BRedOnOff"},
			["Button 5-5"]={template="BRedOnOff"},
			["Fader 7"]={template="FGain"},
		},
		["HPFilter"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Knob V3"]={template="FMisc"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FEffect"},
			["Knob V6"]={template="FMisc"},
		},
		["BPFilter"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Knob V3"]={template="FMisc"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FEffect"},
			["Knob V6"]={template="FMisc"},
		},
		["LPFilter"]={
			["Button 2-1"]={template="BFilterPage"},
			["Button 3-1"]={template="BFilterPage"},
			["Button 4-1"]={template="BFilterPage"},
			["Knob V3"]={template="FMisc"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FEffect"},
			["Knob V6"]={template="FMisc"},
		},
		["HPEffects"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FAmount"},
			["Fader 3"]={template="FEffect"},
			["Fader 4"]={template="FEffect"},
			["Knob V6"]={template="FGain"},
			["Fader 7"]={template="FGain"},
		},
		["BPEffects"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FAmount"},
			["Fader 3"]={template="FEffect"},
			["Fader 4"]={template="FEffect"},
			["Knob V6"]={template="FGain"},
			["Fader 7"]={template="FGain"},
		},
		["LPEffects"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FAmount"},
			["Fader 3"]={template="FEffect"},
			["Fader 4"]={template="FEffect"},
			["Knob V6"]={template="FGain"},
			["Fader 7"]={template="FGain"},
		},
		["Delay"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FFreq"},
			["UDVButton 7-2_8-2"]={template="UDFreq"},
			["Button 1-3"]={template="BGreenOnOff"},
			["Fader 4"]={template="FEffect"},
			["Knob V5"]={template="FEffect"},
		},
		["Phaser"]={
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BEffectPage"},
			["Button 6-8"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Fader 2"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
		},
		["AmpEnv"]={
			["Fader 3"]={template="FGain"},
			["Fader 4"]={template="FGain"},
			["Fader 5"]={template="FGain"},
		},
		["DryLevels"]={
			["Fader 2"]={template="FEffect"},
			["Knob V4"]={template="FGain"},
			["Fader 5"]={template="FGain"},
		},
		["FilterEnv"]={
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FFreq"},
		},
		["LFO"]={
			["UDVButton 1-2_2-2"]={template="UDMisc"},
			["Fader 4"]={template="FFreq"},
			["UDVButton 7-4_8-4"]={template="UDFreq"},
			["Button 1-5"]={template="BGreenOnOff"},
		},
	},
