	["RV7000 Advanced Reverb"]={
		["Default"]={
{% if lptype == "pro" %}
{% include "devices/effect/rv7000advancedreverb/pro/confmap_mainmenu.lua" %}
{% endif %}
		},
		["Index"]={
		},
		["Main"]={
			["UDVButton 1-1_2-1"]={template="UDEffect"},
			["Button 1-2"]={template="BRedOnOff"},
			["Button 2-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FEffect"},
			["Fader 4"]={template="FFreq"},
			["Knob V5"]={template="FFreq"},
			["Fader 7"]={template="FEffect"},
		},
		["Reverb"]={
			["UDVButton 1-1_2-1"]={template="UDEffect"},
			["SmallSpace"]={
				["Fader 2"]={template="FEffect"},
				["Fader 3"]={template="FMisc"},
				["UDVButton 7-4_8-4"]={template="UDEffect"},
				["Fader 5"]={template="FFreq"},
				["Fader 6"]={template="FEffect"},
				["Fader 7"]={template="FFreq"},
				["Fader 8"]={template="FMisc"},
			},
			["Room"]={
				["Fader 2"]={template="FEffect"},
				["Fader 3"]={template="FEffect"},
				["UDVButton 7-4_8-4"]={template="UDEffect"},
				["Fader 5"]={template="FEffect"},
				["Fader 6"]={template="FEffect"},
				["Fader 7"]={template="FFreq"},
				["Fader 8"]={template="FMisc"},
			},
			["Hall"]={
				["Fader 2"]={template="FEffect"},
				["Fader 3"]={template="FEffect"},
				["UDVButton 7-4_8-4"]={template="UDEffect"},
				["Fader 5"]={template="FEffect"},
				["Fader 6"]={template="FEffect"},
				["Fader 7"]={template="FFreq"},
				["Fader 8"]={template="FMisc"},
			},
			["Arena"]={
				["Fader 2"]={template="FEffect"},
				["Fader 3"]={template="FEffect"},
				["Fader 4"]={template="FFreq"},
				["Fader 5"]={template="FFreq"},
				["Fader 6"]={template="FAmount"},
				["Fader 7"]={template="FFreq"},
				["Fader 8"]={template="FAmount"},
			},
			["Plate"]={
				["Fader 5"]={template="FFreq"},
				["Fader 7"]={template="FFreq"},
			},
			["Spring"]={
				["Fader 2"]={template="FEffect"},
				["Fader 3"]={template="FEffect"},
				["Fader 4"]={template="FFreq"},
				["Fader 5"]={template="FFreq"},
				["Button 8-6"]={template="BRedOnOff"},
				["Fader 7"]={template="FFreq"},
				["Fader 8"]={template="FAmount"},
			},
			["Echo"]={
				["Fader 2"]={template="FEffect"},
				["UDVButton 7-2_8-2"]={template="UDEffect"},
				["Fader 3"]={template="FEffect"},
				["Button 8-4"]={template="BRedOnOff"},
				["Fader 5"]={template="FFreq"},
				["Fader 6"]={template="FEffect"},
				["Fader 7"]={template="FFreq"},
			},
			["MultiTap"]={
				["Button 8-2"]={template="BRedOnOff"},
				["Fader 3"]={template="FEffect"},
				["Fader 4"]={template="FFreq"},
				["UDVButton 7-5_8-5"]={template="UDEffect"},
				["Fader 6"]={template="FFreq"},
				["UDVButton 7-6_8-6"]={template="UDFreq"},
				["Fader 7"]={template="FAmount"},
				["Knob V8"]={template="FAmount"},
			},
			["Reverse"]={
				["Fader 2"]={template="FEffect"},
				["UDVButton 7-2_8-2"]={template="UDEffect"},
				["Fader 3"]={template="FEffect"},
				["Button 8-6"]={template="BRedOnOff"},
				["Fader 5"]={template="FEffect"},
			},
			["Convolution"]={
				["UDVButton 7-2_8-2"]={template="UDEffect"},
				["Fader 3"]={template="FEffect"},
				["Knob V4"]={template="FEffect"},
				["Fader 5"]={template="FFreq"},
				["UDVButton 7-6_8-6"]={template="UDAmount"},
				["Knob V7"]={template="FFreq"},
				["Fader 8"]={template="FGain"},
			},
		},
		["Eq"]={
			["Knob V2"]={template="FGain"},
			["Fader 3"]={template="FFreq"},
			["Knob V5"]={template="FGain"},
			["Fader 6"]={template="FFreq"},
			["Fader 7"]={template="FEffect"},
		},
		["Gate"]={
			["Fader 1"]={template="FEffect"},
			["Fader 2"]={template="FEffect"},
			["Button 8-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FFreq"},
			["Fader 5"]={template="FEffect"},
			["Fader 6"]={template="FEffect"},
			["Fader 7"]={template="FEffect"},
		},
	},
