	["Note Echo"]={
		["Default"]={
{% include "devices/player/noteecho/"+lptype+"/confmap_mainmenu.lua" %}
			-- On/Off
			["Button 1-1"]={template="BGreenOnOff"},
			["UDVButton 1-3_2-3"]={template="UDPerf"},
			["Button 1-4"]={template="BPerfOnOff"},
			["UDVButton 1-5_2-5"]={template="UDPerf"},
			["Knob H3"]={template="FPerf"},
			["Knob H4"]={template="FPerf"},
			["Button 5-1"]={template="BPerfOnOff"},
			["Button 6-1"]={template="BPerfOnOff"},
			["Button 6-2"]={template="BPerfOnOff"},
			["Button 6-3"]={template="BPerfOnOff"},
			["Button 6-4"]={template="BPerfOnOff"},
			["Button 6-5"]={template="BPerfOnOff"},
			["Button 6-6"]={template="BPerfOnOff"},
			["Button 6-7"]={template="BPerfOnOff"},
			["Button 6-8"]={template="BPerfOnOff"},
			["Button 7-1"]={template="BPerfOnOff"},
			["Button 7-2"]={template="BPerfOnOff"},
			["Button 7-3"]={template="BPerfOnOff"},
			["Button 7-4"]={template="BPerfOnOff"},
			["Button 7-5"]={template="BPerfOnOff"},
			["Button 7-6"]={template="BPerfOnOff"},
			["Button 7-7"]={template="BPerfOnOff"},
			["Button 7-8"]={template="BPerfOnOff"},
			["Button 8-1"]={template="BPerfOnOff"},
		},
	},
