                        ["Button B1"]={template="BMainPage"},
                        ["Button B2"]={template="BOscPage"},
                        ["Button B3"]={template="BOscPage"},
                        ["Button B4"]={template="BOscPage"},
                        ["Button B5"]={template="BOscPage"},
                        ["Button B6"]={template="BOscPage"},
                        ["Button B7"]={template="BOscPage"},
                        ["Button B8"]={template="BLFOPage"},
