	["Europa"]={
		["Default"]={
{% if lptype == "mini" %}
			["Button 1-1"]={template="BMainPage", helptext="Goto Main"},
			["Button 2-1"]={template="BOscPage", helptext="Goto Engine 1"},
			["Button 3-1"]={template="BOscPage", helptext="Goto Engine 2"},
			["Button 4-1"]={template="BOscPage", helptext="Goto Engine 3"},
{% else %}
			["Button B1"]={template="BMainPage", helptext="Goto Main"},
			["Button B2"]={template="BOscPage", helptext="Goto Engine 1"},
			["Button B3"]={template="BOscPage", helptext="Goto Engine 2"},
			["Button B4"]={template="BOscPage", helptext="Goto Engine 3"},
			["Button B5"]={template="BAmpPage", helptext="Goto Mixer"},
			["Button B6"]={template="BAmpPage", helptext="Goto Amp"},
			["Button B7"]={template="BFilterPage", helptext="Goto Filter"},
			["Button B8"]={template="BEffectPage", helptext="Goto Effects"},
{% endif %}
		},
		["Main"]={
			["UDVButton 7-2_8-2"]={template="UDPerf2"},
			["UDVButton 7-3_8-3"]={template="UDPerf"},
			["Fader 4"]={template="FPerf"},
			["UDVButton 7-7_8-7"]={template="UDAmount"},
			["Fader 8"]={template="FGain"},
		},
		["Index"]={
			["Button 7-1"]={template="BPerformancePage"},
			["Button 7-2"]={template="BPerformancePage"},
			["Button 7-3"]={template="BPerformancePage"},
			["Button 7-4"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["Button 8-2"]={template="BPerformancePage"},
			["Button 8-3"]={template="BPerformancePage"},
			["Button 8-4"]={template="BPerformancePage"},
			["Button 5-5"]={template="BFilterPage"},
			["Button 2-7"]={template="BEffect2Page"},
			["Button 3-7"]={template="BEffect2Page"},
			["Button 4-7"]={template="BEffect2Page"},
		},
		["Mixer"]={
			["Fader 2"]={template="FGain"},
			["Knob V3"]={template="FGain"},
			["Fader 4"]={template="FGain"},
			["Knob V5"]={template="FGain"},
			["Fader 6"]={template="FGain"},
			["Knob V7"]={template="FGain"},
		},
		["Filter"]={
			["Button 5-1"]={template="BRedOnOff"},
			["Button 6-1"]={template="BRedOnOff"},
			["Button 7-1"]={template="BRedOnOff"},
			["UDVButton 1-2_2-2"]={template="UDFreq", inverted=true},
			["Fader 3"]={template="FGain"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FFreq"},
			["UDVButton 1-6_2-6"]={template="UDMisc"},
			["UDVButton 3-6_4-6"]={template="UDMisc"},
			["UDVButton 5-6_6-6"]={template="UDMisc"},
			["UDVButton 3-7_4-7"]={template="UDMisc", inverted=true},
		},
		["Amp"]={
			["Knob V2"]={template="FGain"},
			["Fader 3"]={template="FGain"},
			["Fader 4"]={template="FMisc"},
			["Fader 5"]={template="FGain"},
			["Fader 6"]={template="FGain"},
			["Fader 7"]={template="FGain"},
			["Fader 8"]={template="FGain"},
		},
		["Eng *"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDFreq"},
			["UDVButton 3-3_4-3"]={template="UDFreq"},
			["UDVButton 5-3_6-3"]={template="UDFreq"},
			["UDVButton 1-4_2-4"]={template="UDAmount", inverted=true},
			["UDVButton 7-6_8-6"]={template="UDMisc", inverted=true},
			["Fader 5"]={template="FAmount"},
			["Fader 7"]={template="FMisc"},
			["Fader 8"]={template="FMisc"},
{% include "devices/instrument/europa/europa-bottommenu-osc.lua" %}
		},
		["Eng * Mod *"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDAmount", inverted=true},
			["Fader 4"]={template="FAmount"},
			["Fader 5"]={template="FMisc"},
			["UDVButton 7-6_8-6"]={template="UDMisc", inverted=true},
{% include "devices/instrument/europa/europa-bottommenu-osc.lua" %}
		},
		["Eng * Spectral Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 3-2_4-2"]={template="UDFreq", inverted=true},
			["Fader 3"]={template="FFreq"},
			["Fader 4"]={template="FEffect"},
			["Fader 5"]={template="FMisc"},
			["Fader 6"]={template="FMisc"},
			["UDVButton 7-7_8-7"]={template="UDMisc", inverted=true},
			["Fader 8"]={template="FMisc"},
{% include "devices/instrument/europa/europa-bottommenu-osc.lua" %}
		},
		["Eng * Harmonics"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDAmount", inverted=true},
			["Fader 4"]={template="FMisc"},
			["Fader 5"]={template="FAmount"},
{% include "devices/instrument/europa/europa-bottommenu-osc.lua" %}
		},
		["Eng * Unison"]={
			["Button 1-2"]={template="BRedOnOff"},
			["UDVButton 1-3_2-3"]={template="UDEffect", inverted=true},
			["UDVButton 1-4_2-4"]={template="UDEffect"},
			["Fader 5"]={template="FEffect"},
			["Fader 6"]={template="FFreq"},
			["Fader 7"]={template="FEffect"},
{% include "devices/instrument/europa/europa-bottommenu-osc.lua" %}
		},
		["LFO *"]={
			["Button 5-1"]={template="BLFOPage", helptext="Goto LFO 1"},
			["Button 6-1"]={template="BLFOPage", helptext="Goto LFO 2"},
			["Button 7-1"]={template="BLFOPage", helptext="Goto LFO 3"},
			["UDVButton 1-2_2-2"]={template="UDMisc"},
			["Button 6-2"]={template="BRedOnOff"},
			["Button 7-2"]={template="BRedOnOff"},
			["Button 8-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FFreq"},
			["UDVButton 7-3_8-3"]={template="UDFreq"},
			["Fader 4"]={template="FEffect"},
		},
		["Env *"]={
			["Button 5-1"]={template="BEnvPage", helptext="Goto Env 1"},
			["Button 6-1"]={template="BEnvPage", helptext="Goto Env 2"},
			["Button 7-1"]={template="BEnvPage", helptext="Goto Env 3"},
			["Button 8-1"]={template="BEnvPage", helptext="Goto Env 4"},
			["Fader 3"]={template="FFreq"},
			["UDVButton 7-4_8-4"]={template="UDFreq"},
		},
{% include "devices/instrument/europa/europa-grain-effects.lua" %}
		["Mod Matrix *"]={
			["Button 1-1"]={template="BPerformancePage"},
			["Button 2-1"]={template="BPerformancePage"},
			["Button 3-1"]={template="BPerformancePage"},
			["Button 4-1"]={template="BPerformancePage"},
			["Button 5-1"]={template="BPerformancePage"},
			["Button 6-1"]={template="BPerformancePage"},
			["Button 7-1"]={template="BPerformancePage"},
			["Button 8-1"]={template="BPerformancePage"},
			["UDVButton 1-2_2-2"]={template="UDAmount", inverted=true},
			["Knob V3"]={template="FAmount"},
			["UDVButton 1-4_2-4"]={template="UDEffect", inverted=true},
			["Knob V5"]={template="FEffect"},
			["UDVButton 1-6_2-6"]={template="UDEffect", inverted=true},
			["Knob V7"]={template="FEffect"},
			["UDVButton 1-8_2-8"]={template="UDMisc", inverted=true},
		},
	},
