local item_conf_map = {
{% include "include/confmap_default.lua" %}
{% include "reason/reason-master-section.lua" %}
{% include "reason/reason-mix-channel.lua" %}
{% include "instrument/kong.lua" %}
{% include "instrument/redrum.lua" %}
{% include "instrument/thor.lua" %}
{% include "instrument/combinator.lua" %}
{% include "instrument/drrex.lua" %}
{% include "instrument/id8.lua" %}
{% include "instrument/malstrom.lua" %}
{% include "instrument/nnxt.lua" %}
{% include "instrument/nn19.lua" %}
{% include "instrument/subtractor.lua" %}
{% include "instrument/revival.lua" %}
{% include "instrument/antidote.lua" %}
{% include "instrument/px7.lua" %}
{% include "instrument/parsec.lua" %}
{% include "instrument/europa.lua" %}
{% include "instrument/grain.lua" %}
{% include "instrument/radicalpiano.lua" %}
{% include "instrument/klang.lua" %}
{% include "instrument/pangea.lua" %}
{% include "instrument/humana.lua" %}
{% include "effect/audiomatic.lua" %}
{% include "effect/alligator.lua" %}
{% include "effect/bv512digitalvocoder.lua" %}
{% include "effect/cf-101chorus-flanger.lua" %}
{% include "effect/comp-01compressor-limiter.lua" %}
{% include "effect/d-11foldbackdistortion.lua" %}
{% include "effect/ddl-1digitaldelayline.lua" %}
{% include "effect/ecf-42filter.lua" %}
{% include "effect/mclasscompressor.lua" %}
{% include "effect/mclassequalizer.lua" %}
{% include "effect/mclassmaximizer.lua" %}
{% include "effect/mclassstereoimager.lua" %}
{% include "effect/neptunepitchadjuster.lua" %}
{% include "effect/peq-2twobandparametriceq.lua" %}
{% include "effect/ph-90phaser.lua" %}
{% include "effect/polardualpitchshifter.lua" %}
{% include "effect/pulveriser.lua" %}
{% include "effect/rv-7digitalreverb.lua" %}
{% include "effect/rv7000advancedreverb.lua" %}
{% include "effect/saturationknob.lua" %}
{% include "effect/scream4distortion.lua" %}
{% include "effect/softtubeamp.lua" %}
{% include "effect/softtubebassamp.lua" %}
{% include "effect/synchronous.lua" %}
{% include "effect/theecho.lua" %}
{% include "effect/un-16unison.lua" %}
{% include "utilities/rpg8.lua" %}
{% include "utilities/matrix.lua" %}
}	
