                        ["Button B1"]={template="BMainPage"},
                        ["Button B2"]={template="BAmpPage"},
                        ["Button B3"]={template="BFilterPage"},
                        ["Button B4"]={template="BLFOPage"},
                        ["Button B6"]={template="BEffectPage"},
                        ["Button B7"]={template="BEffectPage"},
                        ["Button B8"]={template="BEffectPage"},
