                        ["Button 6-8"]={template="BAmpPage"},
                        ["Button 7-8"]={template="BMute"},
                        ["Button 8-8"]={template="BSolo"},
			["Channel"]={
                        	["Button A1"]={template="BAmpPage"},
                        	["Button A2"]={template="BAmpPage"},
                        	["Button A3"]={template="BAmpPage"},
                        	["Button A4"]={template="BAmpPage"},
                        	["Button A5"]={template="BAmpPage"},
                        	["Button A6"]={template="BAmpPage"},
                        	["Button A7"]={template="BAmpPage"},
			},
			["Mute"]={
                        	["Button A1"]={template="BMute"},
                        	["Button A2"]={template="BMute"},
                        	["Button A3"]={template="BMute"},
                        	["Button A4"]={template="BMute"},
                        	["Button A5"]={template="BMute"},
                        	["Button A6"]={template="BMute"},
                        	["Button A7"]={template="BMute"},
			},
			["Solo"]={
                        	["Button A1"]={template="BSolo"},
                        	["Button A2"]={template="BSolo"},
                        	["Button A3"]={template="BSolo"},
                        	["Button A4"]={template="BSolo"},
                        	["Button A5"]={template="BSolo"},
                        	["Button A6"]={template="BSolo"},
                        	["Button A7"]={template="BSolo"},
			},
