	["Mix Channel"]={
		["Default"]={
		},
		["Main"]={
			["Button 1-1"]={template="BMute"},
			["Button 1-2"]={template="BSolo"},
			["Fader 4"]={template="FOrange"},
			["Knob V5"]={template="FRed"},
		},
		["Index"]={
			["Button 1-8"]={template="BAmpPage"},
			["Button 2-8"]={template="BEffectPage"},
			["Button 3-8"]={template="BEffectPage"},
			["Button 4-8"]={template="BFilterModPage"},
			["Button 5-8"]={template="BFilterModPage"},
			["Button 6-8"]={template="BFilterPage"},
			["Button 7-7"]={template="BEffectPage"},
			["Button 7-8"]={template="BEffectPage"},
			["Button 8-8"]={template="BEffect2Page"},
		},
		["Input"]={
			["Knob V2"]={template="FRed"},
			["Button 1-3"]={template="BRedOnOff"},
			["Button 1-4"]={template="BRedOnOff"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 1-7"]={template="BRedOnOff"},
		},
		["Compressor"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 4-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Button 1-6"]={template="BRedOnOff"},
			["Meter 8"]={template="FYellow"},
		},
		["Gate"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 4-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FOrange"},
			["Fader 4"]={template="FOrange"},
			["Fader 5"]={template="FYellow"},
			["Fader 6"]={template="FYellow"},
			["Button 1-7"]={template="BRedOnOff"},
			["Meter 8"]={template="FGreen"},
		},
		["Filter"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Fader 3"]={template="FGreen"},
			["Button 1-4"]={template="BRedOnOff"},
			["Fader 5"]={template="FGreen"},
			["Button 1-7"]={template="BRedOnOff"},
		},
		["Equalizer High"]={
			["Button 1-1"]={template="BRedOnOff"},
			["Button 4-1"]={template="BRedOnOff"},
			["Knob V3"]={template="FRed"},
			["Fader 4"]={template="FGreen"},
			["Fader 5"]={template="FOrange"},
			["Button 1-6"]={template="BRedOnOff"},
			["Knob V7"]={template="FRed"},
			["Fader 8"]={template="FGreen"},
		},
		["Equalizer Low"]={
			["Button 1-1"]={template="BRedOnOff"},
			["Button 4-1"]={template="BRedOnOff"},
			["Button 1-2"]={template="BRedOnOff"},
			["Knob V3"]={template="FRed"},
			["Fader 4"]={template="FGreen"},
			["Knob V6"]={template="FRed"},
			["Fader 7"]={template="FGreen"},
			["Fader 8"]={template="FOrange"},
		},
		["Insert"]={
			["Button 1-2"]={template="BRedOnOff"},
			["Button 5-2"]={template="BRedOnOff"},
			["Button 6-2"]={template="BRedOnOff"},
			["Button 7-2"]={template="BRedOnOff"},
			["Button 8-2"]={template="BRedOnOff"},
		},
		["Send *"]={
			["Button 7-1"]={template="BEffectPage"},
			["Button 8-1"]={template="BEffectPage"},
			["Button 1-1"]={template="BRedOnOff"},
			["Button 2-1"]={template="BRedOnOff"},
			["Fader 2"]={template="FGreen"},
			["Button 1-3"]={template="BRedOnOff"},
			["Button 2-3"]={template="BRedOnOff"},
			["Fader 4"]={template="FGreen"},
			["Button 1-5"]={template="BRedOnOff"},
			["Button 2-5"]={template="BRedOnOff"},
			["Fader 6"]={template="FGreen"},
			["Button 1-7"]={template="BRedOnOff"},
			["Button 2-7"]={template="BRedOnOff"},
			["Fader 8"]={template="FGreen"},
		},
	},
